import { createRouter } from "@tanstack/react-router";

// routeTree.gen.ts is auto-generated by the tanstackStart Vite plugin.
// Run `vibe dev --tanstack` once to generate it.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- file is generated on first `vite dev` run
import { routeTree } from "./routeTree.gen";

export function getRouter(): ReturnType<typeof createRouter> {
  return createRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
    defaultNotFoundComponent: () => null,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
