import { createRouter } from "@tanstack/react-router";

// routeTree.gen.ts is auto-generated by the tanstackStart Vite plugin.
// Run `vibe dev --tanstack` once to generate it.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- file is generated on first `vite dev` run
import { routeTree } from "./routeTree.gen";

export function getRouter(): ReturnType<typeof createRouter> {
  return createRouter({
    routeTree,
    defaultPreload: false,
    scrollRestoration: true,
    defaultNotFoundComponent: () => null,
    // During initial hydration, code-split route components suspend briefly
    // while their lazy chunk loads. Without a pending component, the Suspense
    // boundary shows nothing (blank flash). Setting a 0ms pending delay and
    // no pending component keeps existing SSR content visible until the chunk
    // is ready — React 18 will paint the SSR content then swap in-place.
    defaultPendingMs: 0,
    defaultPendingMinMs: 0,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
// test
