# syntax=docker/dockerfile:1

# Base stage with Bun
FROM oven/bun:1.3.0-alpine AS base
WORKDIR /app

# Install Node.js for Next.js build compatibility
RUN apk add --no-cache nodejs

# Build args - accept all env vars
ARG VIBE_CLI_USER_EMAIL
ARG NEXT_PUBLIC_DEBUG_PRODUCTION
ARG ENABLE_ANALYTICS
ARG DATABASE_URL
ARG NODE_TLS_REJECT_UNAUTHORIZED
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_TEST_SERVER_URL
ARG NODE_ENV
ARG JWT_SECRET_KEY
ARG CRON_SECRET
ARG GOOGLE_SERVICE_ACCOUNT_EMAIL
ARG GOOGLE_PRIVATE_KEY
ARG GOOGLE_CALENDAR_ID_DEFAULT
ARG OPENROUTER_API_KEY
ARG UNCENSORED_AI_API_KEY
ARG EDEN_AI_API_KEY
ARG FREEDOMGPT_API_KEY
ARG GAB_AI_API_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPPORT_EMAIL_DE
ARG NEXT_PUBLIC_SUPPORT_EMAIL_PL
ARG NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL
ARG EMAIL_FROM_EMAIL
ARG EMAIL_FROM
ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_SECURE
ARG EMAIL_USER
ARG EMAIL_PASS
ARG LEADS_EMAIL_FROM_EMAIL
ARG LEADS_EMAIL_HOST
ARG LEADS_EMAIL_PORT
ARG LEADS_EMAIL_SECURE
ARG LEADS_EMAIL_USER
ARG LEADS_EMAIL_PASS
ARG SMS_PROVIDER
ARG SMS_FROM_NUMBER
ARG IMAP_SEED_ACCOUNT_NAME
ARG IMAP_SEED_EMAIL
ARG IMAP_SEED_HOST
ARG IMAP_SEED_USERNAME
ARG IMAP_SEED_PASSWORD
ARG IMAP_SEED_PORT
ARG IMAP_SEED_SECURE
ARG NEXT_PUBLIC_GA_ID
ARG BRAVE_SEARCH_API_KEY
ARG NOWPAYMENTS_API_KEY
ARG NOWPAYMENTS_IPN_SECRET

COPY . .

# Set all environment variables for build
ENV VIBE_CLI_USER_EMAIL=$VIBE_CLI_USER_EMAIL
ENV NEXT_PUBLIC_DEBUG_PRODUCTION=$NEXT_PUBLIC_DEBUG_PRODUCTION
ENV ENABLE_ANALYTICS=$ENABLE_ANALYTICS
ENV DATABASE_URL=$DATABASE_URL
ENV NODE_TLS_REJECT_UNAUTHORIZED=$NODE_TLS_REJECT_UNAUTHORIZED
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_TEST_SERVER_URL=$NEXT_PUBLIC_TEST_SERVER_URL
ENV NODE_ENV=$NODE_ENV
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV CRON_SECRET=$CRON_SECRET
ENV GOOGLE_SERVICE_ACCOUNT_EMAIL=$GOOGLE_SERVICE_ACCOUNT_EMAIL
ENV GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY
ENV GOOGLE_CALENDAR_ID_DEFAULT=$GOOGLE_CALENDAR_ID_DEFAULT
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV UNCENSORED_AI_API_KEY=$UNCENSORED_AI_API_KEY
ENV EDEN_AI_API_KEY=$EDEN_AI_API_KEY
ENV FREEDOMGPT_API_KEY=$FREEDOMGPT_API_KEY
ENV GAB_AI_API_KEY=$GAB_AI_API_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPPORT_EMAIL_DE=$NEXT_PUBLIC_SUPPORT_EMAIL_DE
ENV NEXT_PUBLIC_SUPPORT_EMAIL_PL=$NEXT_PUBLIC_SUPPORT_EMAIL_PL
ENV NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL=$NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL
ENV EMAIL_FROM_EMAIL=$EMAIL_FROM_EMAIL
ENV EMAIL_FROM=$EMAIL_FROM
ENV EMAIL_HOST=$EMAIL_HOST
ENV EMAIL_PORT=$EMAIL_PORT
ENV EMAIL_SECURE=$EMAIL_SECURE
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS
ENV LEADS_EMAIL_FROM_EMAIL=$LEADS_EMAIL_FROM_EMAIL
ENV LEADS_EMAIL_HOST=$LEADS_EMAIL_HOST
ENV LEADS_EMAIL_PORT=$LEADS_EMAIL_PORT
ENV LEADS_EMAIL_SECURE=$LEADS_EMAIL_SECURE
ENV LEADS_EMAIL_USER=$LEADS_EMAIL_USER
ENV LEADS_EMAIL_PASS=$LEADS_EMAIL_PASS
ENV SMS_PROVIDER=$SMS_PROVIDER
ENV SMS_FROM_NUMBER=$SMS_FROM_NUMBER
ENV IMAP_SEED_ACCOUNT_NAME=$IMAP_SEED_ACCOUNT_NAME
ENV IMAP_SEED_EMAIL=$IMAP_SEED_EMAIL
ENV IMAP_SEED_HOST=$IMAP_SEED_HOST
ENV IMAP_SEED_USERNAME=$IMAP_SEED_USERNAME
ENV IMAP_SEED_PASSWORD=$IMAP_SEED_PASSWORD
ENV IMAP_SEED_PORT=$IMAP_SEED_PORT
ENV IMAP_SEED_SECURE=$IMAP_SEED_SECURE
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV BRAVE_SEARCH_API_KEY=$BRAVE_SEARCH_API_KEY
ENV NEXT_TELEMETRY_DISABLED=1
ENV NOWPAYMENTS_API_KEY=$NOWPAYMENTS_API_KEY
ENV NOWPAYMENTS_IPN_SECRET=$NOWPAYMENTS_IPN_SECRET

# Install dependencies (skip prepare scripts that may fail in Docker)
RUN bun install --frozen-lockfile

# Build using vibe CLI
RUN bun src/app/api/[locale]/system/unified-interface/cli/vibe-runtime.ts build

ENV NODE_ENV=production

# Expose port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the application using vibe CLI
CMD ["bun", "src/app/api/[locale]/system/unified-interface/cli/vibe-runtime.ts", "start"]
