# syntax=docker/dockerfile:1

# Base stage with Bun
FROM oven/bun:1.3.0-alpine AS base
WORKDIR /app

# Install Node.js for Next.js build compatibility
RUN apk add --no-cache nodejs

# BEGIN_GENERATED_ENV_ARGS
ARG PROJECT_ROOT
ARG DATABASE_URL
ARG LOCAL_MODE_DATABASE_URL
ARG LOCAL_MODE_APP_URL
ARG JWT_SECRET_KEY
ARG CRON_SECRET
ARG THEA_REMOTE_URL
ARG THEA_REMOTE_API_KEY
ARG THEA_REMOTE_LEAD_ID
ARG ENABLE_ANALYTICS
ARG VIBE_ADMIN_USER_EMAIL
ARG VIBE_ADMIN_USER_PASSWORD
ARG VIBE_CLI_LOCALE
ARG NODE_ENV
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_PROJECT_URL
ARG NEXT_PUBLIC_LOCAL_MODE
ARG NEXT_PUBLIC_LOCAL_MODE_APP_URL
ARG NEXT_PUBLIC_TEST_SERVER_URL
ARG NEXT_PUBLIC_DEBUG_PRODUCTION
ARG OPENROUTER_API_KEY
ARG UNCENSORED_AI_API_KEY
ARG FREEDOMGPT_API_KEY
ARG GAB_AI_API_KEY
ARG VENICE_AI_API_KEY
ARG EDEN_AI_API_KEY
ARG BRAVE_SEARCH_API_KEY
ARG KAGI_API_KEY
ARG SCRAPPEY_API_KEY
ARG CHAT_STORAGE_TYPE
ARG CHAT_STORAGE_PATH
ARG S3_ENDPOINT
ARG S3_REGION
ARG S3_BUCKET
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY
ARG S3_PUBLIC_URL_BASE
ARG NEXT_PUBLIC_SUPPORT_EMAIL_DE
ARG NEXT_PUBLIC_SUPPORT_EMAIL_PL
ARG NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL
ARG EMAIL_FROM_EMAIL
ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_SECURE
ARG EMAIL_USER
ARG EMAIL_PASS
ARG IMAP_SEED_ACCOUNT_NAME
ARG IMAP_SEED_EMAIL
ARG IMAP_SEED_HOST
ARG IMAP_SEED_USERNAME
ARG IMAP_SEED_PASSWORD
ARG IMAP_SEED_PORT
ARG IMAP_SEED_SECURE
ARG LEADS_EMAIL_FROM_EMAIL
ARG LEADS_EMAIL_HOST
ARG LEADS_EMAIL_PORT
ARG LEADS_EMAIL_SECURE
ARG LEADS_EMAIL_USER
ARG LEADS_EMAIL_PASS
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG NOWPAYMENTS_API_KEY
ARG NOWPAYMENTS_IPN_SECRET
ARG NOWPAYMENTS_API_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG SMS_PROVIDER
ARG SMS_FROM_NUMBER
ARG SMS_MAX_LENGTH
ARG SMS_MAX_RETRY_ATTEMPTS
ARG SMS_RETRY_DELAY_MS
ARG ADMIN_NOTIFICATION_PHONE
ARG MESSAGEBIRD_ACCESS_KEY
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG SMS_HTTP_API_URL
ARG SMS_HTTP_API_KEY
ARG SMS_HTTP_API_METHOD
ARG SMS_HTTP_PHONE_REGEX
ARG SMS_HTTP_TO_FIELD
ARG SMS_HTTP_MESSAGE_FIELD
ARG SMS_HTTP_FROM_FIELD
ARG SMS_HTTP_RESPONSE_ID_FIELD
ARG SMS_HTTP_CUSTOM_HEADERS
ARG SMS_HTTP_AUTH_SCHEME
ARG SMS_HTTP_CONTENT_TYPE
ARG WHATSAPP_PHONE_NUMBER_ID
ARG WHATSAPP_ACCESS_TOKEN
ARG TELEGRAM_BOT_TOKEN
ARG VERCEL
ARG VERCEL_REGION
ARG VERCEL_URL
ARG AWS_LAMBDA_FUNCTION_NAME
ARG NETLIFY
ARG NETLIFY_SITE_NAME
ARG CLOUDFLARE_WORKERS
ARG RAILWAY_ENVIRONMENT
ARG PULSE_INTERVAL_MINUTES

ENV PROJECT_ROOT=$PROJECT_ROOT
ENV DATABASE_URL=$DATABASE_URL
ENV LOCAL_MODE_DATABASE_URL=$LOCAL_MODE_DATABASE_URL
ENV LOCAL_MODE_APP_URL=$LOCAL_MODE_APP_URL
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV CRON_SECRET=$CRON_SECRET
ENV THEA_REMOTE_URL=$THEA_REMOTE_URL
ENV THEA_REMOTE_API_KEY=$THEA_REMOTE_API_KEY
ENV THEA_REMOTE_LEAD_ID=$THEA_REMOTE_LEAD_ID
ENV ENABLE_ANALYTICS=$ENABLE_ANALYTICS
ENV VIBE_ADMIN_USER_EMAIL=$VIBE_ADMIN_USER_EMAIL
ENV VIBE_ADMIN_USER_PASSWORD=$VIBE_ADMIN_USER_PASSWORD
ENV VIBE_CLI_LOCALE=$VIBE_CLI_LOCALE
ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_PROJECT_URL=$NEXT_PUBLIC_PROJECT_URL
ENV NEXT_PUBLIC_LOCAL_MODE=$NEXT_PUBLIC_LOCAL_MODE
ENV NEXT_PUBLIC_LOCAL_MODE_APP_URL=$NEXT_PUBLIC_LOCAL_MODE_APP_URL
ENV NEXT_PUBLIC_TEST_SERVER_URL=$NEXT_PUBLIC_TEST_SERVER_URL
ENV NEXT_PUBLIC_DEBUG_PRODUCTION=$NEXT_PUBLIC_DEBUG_PRODUCTION
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV UNCENSORED_AI_API_KEY=$UNCENSORED_AI_API_KEY
ENV FREEDOMGPT_API_KEY=$FREEDOMGPT_API_KEY
ENV GAB_AI_API_KEY=$GAB_AI_API_KEY
ENV VENICE_AI_API_KEY=$VENICE_AI_API_KEY
ENV EDEN_AI_API_KEY=$EDEN_AI_API_KEY
ENV BRAVE_SEARCH_API_KEY=$BRAVE_SEARCH_API_KEY
ENV KAGI_API_KEY=$KAGI_API_KEY
ENV SCRAPPEY_API_KEY=$SCRAPPEY_API_KEY
ENV CHAT_STORAGE_TYPE=$CHAT_STORAGE_TYPE
ENV CHAT_STORAGE_PATH=$CHAT_STORAGE_PATH
ENV S3_ENDPOINT=$S3_ENDPOINT
ENV S3_REGION=$S3_REGION
ENV S3_BUCKET=$S3_BUCKET
ENV S3_ACCESS_KEY_ID=$S3_ACCESS_KEY_ID
ENV S3_SECRET_ACCESS_KEY=$S3_SECRET_ACCESS_KEY
ENV S3_PUBLIC_URL_BASE=$S3_PUBLIC_URL_BASE
ENV NEXT_PUBLIC_SUPPORT_EMAIL_DE=$NEXT_PUBLIC_SUPPORT_EMAIL_DE
ENV NEXT_PUBLIC_SUPPORT_EMAIL_PL=$NEXT_PUBLIC_SUPPORT_EMAIL_PL
ENV NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL=$NEXT_PUBLIC_SUPPORT_EMAIL_GLOBAL
ENV EMAIL_FROM_EMAIL=$EMAIL_FROM_EMAIL
ENV EMAIL_HOST=$EMAIL_HOST
ENV EMAIL_PORT=$EMAIL_PORT
ENV EMAIL_SECURE=$EMAIL_SECURE
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS
ENV IMAP_SEED_ACCOUNT_NAME=$IMAP_SEED_ACCOUNT_NAME
ENV IMAP_SEED_EMAIL=$IMAP_SEED_EMAIL
ENV IMAP_SEED_HOST=$IMAP_SEED_HOST
ENV IMAP_SEED_USERNAME=$IMAP_SEED_USERNAME
ENV IMAP_SEED_PASSWORD=$IMAP_SEED_PASSWORD
ENV IMAP_SEED_PORT=$IMAP_SEED_PORT
ENV IMAP_SEED_SECURE=$IMAP_SEED_SECURE
ENV LEADS_EMAIL_FROM_EMAIL=$LEADS_EMAIL_FROM_EMAIL
ENV LEADS_EMAIL_HOST=$LEADS_EMAIL_HOST
ENV LEADS_EMAIL_PORT=$LEADS_EMAIL_PORT
ENV LEADS_EMAIL_SECURE=$LEADS_EMAIL_SECURE
ENV LEADS_EMAIL_USER=$LEADS_EMAIL_USER
ENV LEADS_EMAIL_PASS=$LEADS_EMAIL_PASS
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV NOWPAYMENTS_API_KEY=$NOWPAYMENTS_API_KEY
ENV NOWPAYMENTS_IPN_SECRET=$NOWPAYMENTS_IPN_SECRET
ENV NOWPAYMENTS_API_URL=$NOWPAYMENTS_API_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV SMS_PROVIDER=$SMS_PROVIDER
ENV SMS_FROM_NUMBER=$SMS_FROM_NUMBER
ENV SMS_MAX_LENGTH=$SMS_MAX_LENGTH
ENV SMS_MAX_RETRY_ATTEMPTS=$SMS_MAX_RETRY_ATTEMPTS
ENV SMS_RETRY_DELAY_MS=$SMS_RETRY_DELAY_MS
ENV ADMIN_NOTIFICATION_PHONE=$ADMIN_NOTIFICATION_PHONE
ENV MESSAGEBIRD_ACCESS_KEY=$MESSAGEBIRD_ACCESS_KEY
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV TWILIO_REGION=$TWILIO_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV SMS_HTTP_API_URL=$SMS_HTTP_API_URL
ENV SMS_HTTP_API_KEY=$SMS_HTTP_API_KEY
ENV SMS_HTTP_API_METHOD=$SMS_HTTP_API_METHOD
ENV SMS_HTTP_PHONE_REGEX=$SMS_HTTP_PHONE_REGEX
ENV SMS_HTTP_TO_FIELD=$SMS_HTTP_TO_FIELD
ENV SMS_HTTP_MESSAGE_FIELD=$SMS_HTTP_MESSAGE_FIELD
ENV SMS_HTTP_FROM_FIELD=$SMS_HTTP_FROM_FIELD
ENV SMS_HTTP_RESPONSE_ID_FIELD=$SMS_HTTP_RESPONSE_ID_FIELD
ENV SMS_HTTP_CUSTOM_HEADERS=$SMS_HTTP_CUSTOM_HEADERS
ENV SMS_HTTP_AUTH_SCHEME=$SMS_HTTP_AUTH_SCHEME
ENV SMS_HTTP_CONTENT_TYPE=$SMS_HTTP_CONTENT_TYPE
ENV WHATSAPP_PHONE_NUMBER_ID=$WHATSAPP_PHONE_NUMBER_ID
ENV WHATSAPP_ACCESS_TOKEN=$WHATSAPP_ACCESS_TOKEN
ENV TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
ENV VERCEL=$VERCEL
ENV VERCEL_REGION=$VERCEL_REGION
ENV VERCEL_URL=$VERCEL_URL
ENV AWS_LAMBDA_FUNCTION_NAME=$AWS_LAMBDA_FUNCTION_NAME
ENV NETLIFY=$NETLIFY
ENV NETLIFY_SITE_NAME=$NETLIFY_SITE_NAME
ENV CLOUDFLARE_WORKERS=$CLOUDFLARE_WORKERS
ENV RAILWAY_ENVIRONMENT=$RAILWAY_ENVIRONMENT
ENV PULSE_INTERVAL_MINUTES=$PULSE_INTERVAL_MINUTES
# END_GENERATED_ENV_ARGS

ENV NEXT_TELEMETRY_DISABLED=1

COPY . .

# Install dependencies
# Bun download cache avoids re-fetching tarballs; bun install with warm cache ~10-20s vs cold ~2min
# node_modules not cache-mounted: at 1.9GB/183k files, cp-in+cp-out costs ~3min, more than install itself
RUN --mount=type=cache,target=/root/.bun/install/cache,id=next-vibe-bun-cache,sharing=locked \
    bun install --frozen-lockfile

# Build
# /app/.next/cache mounted directly — Next.js webpack/RSC incremental cache persisted across builds
# DB unreachable at build time (docker network only); migrations run via docker compose run in install-docker.sh
RUN --mount=type=cache,target=/app/.next/cache,id=next-vibe-next-cache,sharing=locked \
    bun src/app/api/[locale]/system/unified-interface/cli/vibe-runtime.ts build --migrate=false --seed=false

ENV NODE_ENV=production

# Expose port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the application using vibe CLI (skipPre=true by default: migrations ran at build time)
CMD ["bun", "src/app/api/[locale]/system/unified-interface/cli/vibe-runtime.ts", "start"]
