/**
 * Settings Setup Wizard
 * Step-by-step guided configuration for first-time setup.
 * Shown automatically when needsOnboarding=true, or when user clicks "Setup Wizard".
 */

"use client";
import { cn } from "next-vibe/core/utils/utils";
import { useApiMutation } from "next-vibe/platforms/react/hooks/use-api-mutation";
import { storage } from "next-vibe/ui/lib/storage";
import { Button } from "next-vibe/ui/ui/button";
import { Div } from "next-vibe/ui/ui/div";
import { AlertCircle } from "next-vibe/ui/ui/icons/AlertCircle";
import { Check } from "next-vibe/ui/ui/icons/Check";
import { ChevronLeft } from "next-vibe/ui/ui/icons/ChevronLeft";
import { ChevronRight } from "next-vibe/ui/ui/icons/ChevronRight";
import { Cloud } from "next-vibe/ui/ui/icons/Cloud";
import { LogIn } from "next-vibe/ui/ui/icons/LogIn";
import { RefreshCw } from "next-vibe/ui/ui/icons/RefreshCw";
import { ShieldPlus } from "next-vibe/ui/ui/icons/ShieldPlus";
import type { InputChangeEvent } from "next-vibe/ui/ui/input";
import { Input } from "next-vibe/ui/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "next-vibe/ui/ui/select";
import { Span } from "next-vibe/ui/ui/span";
import { Switch } from "next-vibe/ui/ui/switch";
import {
  useWidgetContext,
  useWidgetLocale,
  useWidgetLogger,
  useWidgetTranslation,
  useWidgetUser,
} from "next-vibe/unified-ui/_shared/use-widget-context";
import type { JSX } from "react";
import React, { useCallback, useEffect, useState } from "react";

import { useProviderAvailability } from "@/app/api/[locale]/agent/env-availability-context";
import instanceEndpoints from "@/app/api/[locale]/remote-connection/[instanceId]/definition";
import { useRemoteConnections } from "@/app/api/[locale]/remote-connection/list/hooks";

import type endpoints from "./definition";
import type { SystemSettingsGetResponseOutput } from "./definition";
import settingsEndpoints from "./definition";

type WizardStep = SystemSettingsGetResponseOutput["wizardSteps"][number];
type Module = SystemSettingsGetResponseOutput["modules"][number];
type Setting = Module["settings"][number];

// Group labels matching onboardingGroup values
const GROUP_LABELS: Record<string, string> = {
  admin: "wizard.steps.admin",
  database: "wizard.steps.database",
  security: "wizard.steps.security",
  ai: "wizard.steps.ai",
};

/** Flatten all settings from all modules into a single lookup map */
function buildSettingsMap(modules: Module[]): Map<string, Setting> {
  const map = new Map<string, Setting>();
  for (const mod of modules) {
    for (const s of mod.settings) {
      map.set(s.key, s);
    }
  }
  return map;
}

/** True if this key is auto-generated (JWT / CRON secrets that have a default) */
function isAutoGenerated(key: string): boolean {
  return key === "JWT_SECRET_KEY" || key === "CRON_SECRET";
}

function StepIndicator({
  steps,
  currentStep,
  t,
}: {
  steps: WizardStep[];
  currentStep: number;
  t: (k: string) => string;
}): JSX.Element {
  return (
    <Div className="flex items-center gap-1 mb-6">
      {steps.map((step, idx) => {
        const isActive = idx === currentStep;
        const isDone = idx < currentStep;
        return (
          <React.Fragment key={step.step}>
            <Div className="flex flex-col items-center gap-1">
              <Div
                className={cn(
                  "w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-colors",
                  isActive && "bg-primary text-primary-foreground",
                  isDone && "bg-success text-white",
                  !isActive && !isDone && "bg-muted text-muted-foreground",
                )}
              >
                {isDone ? <Check className="h-4 w-4" /> : step.step}
              </Div>
              <Span
                className={cn(
                  "text-[10px] text-center hidden sm:block",
                  isActive
                    ? "text-primary font-medium"
                    : "text-muted-foreground",
                )}
              >
                {t(GROUP_LABELS[step.group] ?? step.group)}
              </Span>
            </Div>
            {idx < steps.length - 1 && (
              <Div
                className={cn(
                  "flex-1 h-0.5 mb-4",
                  idx < currentStep ? "bg-success" : "bg-muted",
                )}
              />
            )}
          </React.Fragment>
        );
      })}
    </Div>
  );
}

function EncryptionCallout({ t }: { t: (k: string) => string }): JSX.Element {
  return (
    <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-success/10 border border-success/30 text-xs text-success-foreground mb-2">
      <ShieldPlus className="h-3.5 w-3.5 shrink-0 mt-0.5" />
      <Span>{t("wizard.encryptionNote")}</Span>
    </Div>
  );
}

function AutoGeneratedCallout({
  t,
}: {
  t: (k: string) => string;
}): JSX.Element {
  return (
    <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-info/10 border border-info/20 text-xs text-info mb-2">
      <RefreshCw className="h-3.5 w-3.5 shrink-0 mt-0.5" />
      <Span>{t("wizard.autoGeneratedNote")}</Span>
    </Div>
  );
}

function GenerateKeyButton({
  onGenerate,
}: {
  onGenerate: () => Promise<void>;
}): JSX.Element {
  const [loading, setLoading] = useState(false);
  const handleClick = useCallback(async (): Promise<void> => {
    setLoading(true);
    try {
      await onGenerate();
    } finally {
      setLoading(false);
    }
  }, [onGenerate]);

  return (
    <Button
      variant="outline"
      size="sm"
      className="h-7 text-xs"
      disabled={loading}
      onClick={handleClick}
    >
      <RefreshCw className={cn("h-3 w-3 mr-1", loading && "animate-spin")} />
      {loading ? "Generating..." : "Generate"}
    </Button>
  );
}

function ClaudeCodeField({
  setting,
  t,
}: {
  setting: Setting;
  t: (k: string) => string;
}): JSX.Element {
  const isDetected = setting.value === "true" || setting.isConfigured;
  return (
    <Div className="flex flex-col gap-3 mb-4">
      <Div className="flex items-center gap-1.5">
        <Span className="text-sm font-medium">
          {t("wizard.ai.claudeCodeTitle")}
        </Span>
      </Div>
      <Span className="text-xs text-muted-foreground">
        {t("wizard.ai.claudeCodeDescription")}
      </Span>
      {isDetected ? (
        <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-success/10 border border-success/30 text-xs text-success-foreground">
          <Check className="h-3.5 w-3.5 shrink-0 mt-0.5" />
          <Span>{t("wizard.ai.claudeDetected")}</Span>
        </Div>
      ) : (
        <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-warning/10 border border-warning/30 text-xs text-warning-foreground">
          <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
          <Div className="flex flex-col gap-1">
            <Span className="font-medium">
              {t("wizard.ai.claudeNotDetected")}
            </Span>
            <Span>{t("wizard.ai.claudeInstallHint")}</Span>
          </Div>
        </Div>
      )}
    </Div>
  );
}

function OpenRouterHint({ t }: { t: (k: string) => string }): JSX.Element {
  return (
    <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-info/10 border border-info/20 text-xs text-info mb-2">
      <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
      <Span>{t("wizard.ai.openRouterHint")}</Span>
    </Div>
  );
}

function UnbottledLoginField({
  t,
}: {
  t: (k: string, params?: Record<string, string>) => string;
}): JSX.Element {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  // eslint-disable-next-line i18next/no-literal-string
  const [remoteUrl, setRemoteUrl] = useState("https://unbottled.ai");
  const [error, setError] = useState<string | null>(null);

  const user = useWidgetUser();
  const logger = useWidgetLogger();

  // Connection state is the source of truth — a system inference provider is a
  // remote connection flagged isInferenceProvider, not an env credential.
  const connections = useRemoteConnections(logger, user);
  const provider = connections.read?.data?.connections.find(
    (c) => c.isInferenceProvider,
  );
  const isConnected = provider?.healthStatus === "healthy";
  const isConfiguredButUnhealthy = !!provider && !isConnected;
  const connectedUrl = provider?.remoteUrl ?? "";

  // Connect = create an inference-provider remote connection (settings POST is a
  // thin wrapper over remote-connection/connect with isInferenceProvider: true).
  const connectMutation = useApiMutation(settingsEndpoints.POST, logger, user);
  const disconnectMutation = useApiMutation(
    instanceEndpoints.DELETE,
    logger,
    user,
  );
  const loading = connectMutation.isPending || disconnectMutation.isPending;

  const handleSignIn = useCallback(async (): Promise<void> => {
    setError(null);
    const normalizedUrl = remoteUrl.replace(/\/+$/, "");
    const result = await connectMutation.mutateAsync({
      requestData: { email, password, remoteUrl: normalizedUrl },
    });
    if (!result.success || !result.data?.connected) {
      setError(t("wizard.ai.unbottledLoginFailed"));
      return;
    }
    await connections.read?.refetch();
  }, [email, password, remoteUrl, t, connectMutation, connections]);

  const handleDisconnect = useCallback(async (): Promise<void> => {
    if (!provider) {
      return;
    }
    await disconnectMutation.mutateAsync({
      urlPathParams: { instanceId: provider.instanceId },
    });
    await connections.read?.refetch();
  }, [provider, disconnectMutation, connections]);

  return (
    <Div className="flex flex-col gap-3 mb-4">
      <Div className="flex items-center gap-1.5">
        <Cloud className="h-4 w-4 text-primary shrink-0" />
        <Span className="text-sm font-medium">
          {t("wizard.ai.unbottledTitle")}
        </Span>
      </Div>
      <Span className="text-xs text-muted-foreground">
        {t("wizard.ai.unbottledDescription")}
      </Span>

      {isConnected ? (
        <Div className="flex flex-col gap-2">
          <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-success/10 border border-success/30 text-xs text-success-foreground">
            <Check className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <Span>
              {t("wizard.ai.unbottledConnected", { url: connectedUrl })}
            </Span>
          </Div>
          <Button
            variant="outline"
            size="sm"
            className="w-fit text-xs h-7"
            onClick={handleDisconnect}
          >
            {t("wizard.ai.unbottledDisconnect")}
          </Button>
        </Div>
      ) : isConfiguredButUnhealthy ? (
        <Div className="flex flex-col gap-2">
          <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-warning/10 border border-warning/30 text-xs text-warning-foreground">
            <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
            <Span>{t("wizard.ai.unbottledDisconnected")}</Span>
          </Div>
          <Button
            variant="outline"
            size="sm"
            className="w-fit text-xs h-7"
            onClick={handleDisconnect}
          >
            {t("wizard.ai.unbottledDisconnect")}
          </Button>
        </Div>
      ) : (
        <Div className="flex flex-col gap-2">
          <Input
            className="h-9 text-sm"
            placeholder={t("wizard.ai.unbottledEmail")}
            type="email"
            value={email}
            onChange={(e: InputChangeEvent<"email">): void =>
              setEmail(String(e.target.value ?? ""))
            }
          />
          <Input
            className="h-9 text-sm"
            placeholder={t("wizard.ai.unbottledPassword")}
            type="password"
            value={password}
            onChange={(e: InputChangeEvent<"password">): void =>
              setPassword(String(e.target.value ?? ""))
            }
          />
          <Input
            className="h-9 text-sm font-mono"
            placeholder={t("wizard.ai.unbottledRemoteUrl")}
            value={remoteUrl}
            onChange={(e: InputChangeEvent): void =>
              setRemoteUrl(String(e.target.value ?? ""))
            }
          />

          {error && (
            <Div className="flex items-start gap-2 px-3 py-2 rounded-md bg-destructive/10 border border-destructive/30 text-xs text-destructive">
              <AlertCircle className="h-3.5 w-3.5 shrink-0 mt-0.5" />
              <Span>{error}</Span>
            </Div>
          )}

          <Button
            size="sm"
            className="w-fit"
            disabled={loading || !email || !password}
            onClick={handleSignIn}
          >
            {loading ? (
              <>
                <RefreshCw className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                {t("wizard.ai.unbottledSigningIn")}
              </>
            ) : (
              <>
                <LogIn className="h-3.5 w-3.5 mr-1.5" />
                {t("wizard.ai.unbottledSignIn")}
              </>
            )}
          </Button>
        </Div>
      )}
    </Div>
  );
}

function WizardField({
  setting,
  editedValue,
  onEdit,
  onGenerate,
  t,
}: {
  setting: Setting;
  editedValue: string | undefined;
  onEdit: (key: string, value: string) => void;
  onGenerate?: (key: string) => Promise<void>;
  t: (k: string) => string;
}): JSX.Element {
  if (setting.key === "CLAUDE_CODE_ENABLED") {
    return <ClaudeCodeField setting={setting} t={t} />;
  }
  const autoGen = isAutoGenerated(setting.key);
  const displayValue =
    editedValue ?? (setting.isConfigured ? setting.value : "");

  return (
    <Div className="flex flex-col gap-1.5 mb-4">
      <Div className="flex items-center justify-between">
        <Div className="flex items-center gap-1.5">
          {setting.isSensitive && (
            <ShieldPlus className="h-3 w-3 text-success shrink-0" />
          )}
          <Span className="text-sm font-medium">{setting.key}</Span>
          {setting.onboardingRequired && (
            <Span className="text-[10px] px-1 py-0.5 rounded bg-warning/10 text-warning">
              {t("widget.required")}
            </Span>
          )}
        </Div>
        {autoGen && onGenerate && (
          <GenerateKeyButton
            onGenerate={(): Promise<void> => onGenerate(setting.key)}
          />
        )}
      </Div>

      {setting.comment && (
        <Span className="text-xs text-muted-foreground">{setting.comment}</Span>
      )}

      {setting.isSensitive && !autoGen && <EncryptionCallout t={t} />}
      {autoGen && <AutoGeneratedCallout t={t} />}
      {setting.key === "OPENROUTER_API_KEY" && <OpenRouterHint t={t} />}

      {setting.fieldType === "select" && setting.options?.length ? (
        <Select
          value={displayValue}
          onValueChange={(v): void => onEdit(setting.key, v)}
        >
          <SelectTrigger className="h-9 text-sm font-mono">
            <SelectValue placeholder="Select..." />
          </SelectTrigger>
          <SelectContent>
            {setting.options.map((opt) => (
              <SelectItem key={opt} value={opt}>
                {opt}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      ) : setting.fieldType === "boolean" ? (
        <Div className="flex items-center gap-2">
          <Switch
            checked={displayValue === "true"}
            onCheckedChange={(v): void =>
              onEdit(setting.key, v ? "true" : "false")
            }
          />
          <Span className="text-xs text-muted-foreground font-mono">
            {displayValue === "true"
              ? t("widget.boolTrue")
              : t("widget.boolFalse")}
          </Span>
        </Div>
      ) : setting.isSensitive ? (
        <Input
          type="password"
          className="h-9 text-sm font-mono"
          value={editedValue ?? ""}
          placeholder={
            setting.isConfigured && setting.value !== "change-me-now"
              ? // eslint-disable-next-line i18next/no-literal-string
                "••••••••"
              : setting.example || setting.comment || undefined
          }
          onChange={(e: InputChangeEvent<"password">): void =>
            onEdit(setting.key, String(e.target.value ?? ""))
          }
        />
      ) : (
        <Input
          className="h-9 text-sm font-mono"
          value={editedValue ?? ""}
          placeholder={setting.example || setting.comment || undefined}
          onChange={(e: InputChangeEvent): void =>
            onEdit(setting.key, String(e.target.value ?? ""))
          }
        />
      )}
    </Div>
  );
}

function DoneScreen({
  onGoToSettings,
  t,
}: {
  onGoToSettings: () => void;
  t: (k: string) => string;
}): JSX.Element {
  return (
    <Div className="flex flex-col items-center gap-4 py-8 text-center">
      <Div className="w-16 h-16 rounded-full bg-success/10 flex items-center justify-center">
        <Check className="h-8 w-8 text-success" />
      </Div>
      <Div className="flex flex-col gap-1">
        <Span className="text-xl font-bold">{t("wizard.done")}</Span>
        <Span className="text-sm text-muted-foreground max-w-sm">
          {t("wizard.doneSubtitle")}
        </Span>
      </Div>
      <Button onClick={onGoToSettings}>
        <ChevronRight className="h-4 w-4 mr-1.5" />
        {t("wizard.goToSettings")}
      </Button>
    </Div>
  );
}

interface WizardProps {
  data: SystemSettingsGetResponseOutput;
  onDone: () => void;
}

export function SettingsWizard({ data, onDone }: WizardProps): JSX.Element {
  const t = useWidgetTranslation<typeof endpoints.GET>() as (
    k: string,
  ) => string;
  const locale = useWidgetLocale();
  const user = useWidgetUser();
  const logger = useWidgetLogger();
  const availability = useProviderAvailability();
  const { endpointMutations } = useWidgetContext();

  const { wizardSteps, modules } = data;
  const settingsMap = buildSettingsMap(modules);

  const [currentStep, setCurrentStep] = useState(0);
  const [edits, setEdits] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);

  const totalSteps = wizardSteps.length;
  const activeWizardStep = wizardSteps[currentStep];
  const stepFields = (activeWizardStep?.fields ?? [])
    .map((key) => settingsMap.get(key))
    .filter((s): s is Setting => s !== undefined);

  const handleEdit = useCallback((key: string, value: string): void => {
    setEdits((prev) => ({ ...prev, [key]: value }));
  }, []);

  const handleGenerate = useCallback(
    async (key: string): Promise<void> => {
      if (!user) {
        return;
      }
      try {
        const { apiClient } =
          await import("next-vibe/platforms/react/hooks/store");
        const generateKeyDef =
          await import("next-vibe/env/settings/generate-key/definition");
        const result = await apiClient.fetch(
          generateKeyDef.default.GET,
          logger,
          user,
          undefined,
          undefined,
          locale,
          availability,
        );
        if (result.success && result.data) {
          handleEdit(key, result.data.key);
        }
      } catch {
        // ignore
      }
    },
    [user, logger, locale, handleEdit, availability],
  );

  const saveCurrentStep = useCallback(async (): Promise<void> => {
    if (!user) {
      return;
    }
    const stepKeys = activeWizardStep?.fields ?? [];
    const toSave: Record<string, string> = {};
    for (const key of stepKeys) {
      if (edits[key] !== undefined && edits[key] !== "") {
        toSave[key] = edits[key];
      }
    }
    if (Object.keys(toSave).length === 0) {
      return;
    }

    setSaving(true);
    try {
      const { apiClient } =
        await import("next-vibe/platforms/react/hooks/store");
      const endpointsDef = await import("./definition");
      await apiClient.mutate(
        endpointsDef.PATCH,
        logger,
        user,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        toSave as any,
        undefined,
        locale,
        availability,
      );
      endpointMutations?.read?.refetch?.();
    } finally {
      setSaving(false);
    }
  }, [
    activeWizardStep,
    edits,
    user,
    logger,
    locale,
    availability,
    endpointMutations,
  ]);

  const handleNext = useCallback(async (): Promise<void> => {
    await saveCurrentStep();
    if (currentStep < totalSteps - 1) {
      setCurrentStep((s) => s + 1);
    } else {
      setDone(true);
      await storage.setItem("vibe-wizard-dismissed", "1");
    }
  }, [saveCurrentStep, currentStep, totalSteps]);

  const handleBack = useCallback((): void => {
    setCurrentStep((s) => Math.max(0, s - 1));
  }, []);

  const handleSkip = useCallback(async (): Promise<void> => {
    if (currentStep < totalSteps - 1) {
      setCurrentStep((s) => s + 1);
    } else {
      setDone(true);
      await storage.setItem("vibe-wizard-dismissed", "1");
    }
  }, [currentStep, totalSteps]);

  // Pre-fill auto-generated keys that are already configured
  useEffect(() => {
    for (const step of wizardSteps) {
      for (const key of step.fields) {
        const setting = settingsMap.get(key);
        if (
          setting?.isConfigured &&
          isAutoGenerated(key) &&
          edits[key] === undefined
        ) {
          // Don't pre-fill - they're already set; wizard just confirms
        }
      }
    }
  }, [wizardSteps, settingsMap, edits]);

  if (done) {
    return <DoneScreen onGoToSettings={onDone} t={t} />;
  }

  return (
    <Div className="flex flex-col gap-0">
      <Div className="p-6 pb-2">
        <Div className="mb-1">
          <Span className="text-xl font-bold">{t("wizard.title")}</Span>
        </Div>
        <Span className="text-sm text-muted-foreground">
          {t("wizard.subtitle")}
        </Span>
      </Div>

      <Div className="px-6 pt-4">
        <StepIndicator steps={wizardSteps} currentStep={currentStep} t={t} />
      </Div>

      <Div className="px-6 py-2">
        <Div className="flex items-center justify-between mb-4">
          <Span className="font-semibold text-base">
            {t(
              GROUP_LABELS[activeWizardStep?.group ?? ""] ??
                activeWizardStep?.group ??
                "",
            )}
          </Span>
          <Button
            variant="ghost"
            size="sm"
            className="text-xs h-7"
            onClick={async (): Promise<void> => {
              await storage.setItem("vibe-wizard-dismissed", "1");
              onDone();
            }}
          >
            {t("wizard.viewAllSettings")}
          </Button>
        </Div>

        {stepFields.map((setting) => (
          <WizardField
            key={setting.key}
            setting={setting}
            editedValue={edits[setting.key]}
            onEdit={handleEdit}
            onGenerate={
              isAutoGenerated(setting.key) ? handleGenerate : undefined
            }
            t={t}
          />
        ))}

        {/* System inference provider — a remote connection, not an env var.
            Surfaced in the AI onboarding step so users can connect unbottled.ai
            (or any instance) as their inference provider. */}
        {activeWizardStep?.group === "ai" && <UnbottledLoginField t={t} />}
      </Div>

      <Div className="flex items-center justify-between px-6 py-4 border-t mt-2">
        {currentStep > 0 ? (
          <Button variant="ghost" size="sm" onClick={handleBack}>
            <ChevronLeft className="h-4 w-4 mr-1" />
            {t("wizard.back")}
          </Button>
        ) : (
          <Div />
        )}

        <Div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={handleSkip}>
            {t("wizard.skip")}
          </Button>
          <Button size="sm" disabled={saving} onClick={handleNext}>
            {saving ? (
              <RefreshCw className="h-3.5 w-3.5 mr-1.5 animate-spin" />
            ) : currentStep < totalSteps - 1 ? (
              <>
                {t("wizard.next")}
                <ChevronRight className="h-4 w-4 ml-1" />
              </>
            ) : (
              <>
                <Check className="h-3.5 w-3.5 mr-1.5" />
                {t("wizard.finish")}
              </>
            )}
          </Button>
        </Div>
      </Div>
    </Div>
  );
}
