/**
 * Export Production Env Repository
 *
 * Reads all env modules, decrypts sensitive values,
 * and builds a production-ready .env file string.
 */

import "server-only";

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

import type { ResponseType } from "next-vibe/shared/types/response.schema";
import {
  ErrorResponseTypes,
  fail,
  success,
} from "next-vibe/shared/types/response.schema";
import { parseError } from "next-vibe/shared/utils/parse-error";

import type { EnvExample } from "@/app/api/[locale]/system/unified-interface/shared/env/define-env";
import {
  decryptEnvValue,
  isEncryptedValue,
  loadOrCreateKey,
} from "@/app/api/[locale]/system/unified-interface/shared/env/env-crypto";
import type { EndpointLogger } from "@/app/api/[locale]/system/unified-interface/shared/logger/endpoint";

import type { ExportEnvResponseOutput } from "./definition";
import type { ExportEnvT } from "./i18n";

export class ExportEnvRepository {
  private static readonly SENSITIVE_PATTERNS = [
    "_KEY",
    "_SECRET",
    "_PASS",
    "_TOKEN",
    "_SID",
    "_CREDENTIAL",
    "PASSWORD",
    "JWT_SECRET",
    "CRON_SECRET",
    "ACCESS_KEY",
    "AUTH_TOKEN",
    "DATABASE_URL",
  ];

  private static isSensitiveKey(
    key: string,
    explicitSensitive?: boolean,
  ): boolean {
    if (explicitSensitive !== undefined) {
      return explicitSensitive;
    }
    const upper = key.toUpperCase();
    return ExportEnvRepository.SENSITIVE_PATTERNS.some((p) =>
      upper.includes(p),
    );
  }

  private static getEnvFilePath(): string {
    return join(process.cwd(), ".env");
  }

  private static formatDate(): string {
    return new Date().toISOString().slice(0, 16).replace("T", " ");
  }
  static async exportProdEnv(
    logger: EndpointLogger,
    t: ExportEnvT,
  ): Promise<ResponseType<ExportEnvResponseOutput>> {
    try {
      logger.debug("Generating production env export");

      const { envModules } =
        await import("@/app/api/[locale]/system/generated/env");

      // Read raw .env to get encrypted values (need to decrypt them for prod)
      const envPath = ExportEnvRepository.getEnvFilePath();
      const rawEnvFile = existsSync(envPath)
        ? await readFile(envPath, "utf-8")
        : "";

      // Build a map of raw (potentially encrypted) values from .env file
      const rawEnvMap = new Map<string, string>();
      for (const line of rawEnvFile.split("\n")) {
        const trimmed = line.trim();
        if (trimmed.startsWith("#") || !trimmed.includes("=")) {
          continue;
        }
        const eqIdx = trimmed.indexOf("=");
        const k = trimmed.slice(0, eqIdx);
        const v = trimmed.slice(eqIdx + 1).replace(/^"|"$/g, "");
        rawEnvMap.set(k, v);
      }

      // Load encryption key once
      const cryptoKey = loadOrCreateKey();

      // Collect checklist items (sensitive keys that need manual review)
      const checklistItems: string[] = [];

      const lines: string[] = [];
      const now = ExportEnvRepository.formatDate();

      lines.push(
        "# ============================================================",
      );
      lines.push(`# PRODUCTION ENV — generated by vibe export-env`);
      lines.push(`# Generated: ${now}`);
      lines.push(
        "# ============================================================",
      );
      lines.push("#");
      lines.push("# INSTRUCTIONS:");
      lines.push(
        "#   1. Review every value — sensitive values are shown in plain text",
      );
      lines.push(
        "#   2. Copy to your server:  scp .env.prod user@yourserver:/app/.env",
      );
      lines.push(
        "#   3. Or paste manually:    ssh user@yourserver && nano /app/.env",
      );
      lines.push(
        "#   4. Restart application:  docker-compose -f docker-compose.prod.yml up -d",
      );
      lines.push(
        "# ============================================================",
      );
      lines.push("");
      lines.push("NODE_ENV=production");
      lines.push("");

      const HIDDEN_MODULES = new Set(["serverSystem"]);

      for (const [moduleName, moduleData] of Object.entries(envModules)) {
        if (HIDDEN_MODULES.has(moduleName)) {
          continue;
        }

        const { env, examples } = moduleData as {
          env: Record<string, string | number | boolean | null | undefined>;
          examples: EnvExample[];
        };

        const entries = Object.entries(env).filter(
          ([k]) => k !== "NODE_ENV", // already written above
        );

        if (entries.length === 0) {
          continue;
        }

        lines.push(
          `# ── ${moduleName.toUpperCase()} ──────────────────────────────────────────────────────`,
        );
        lines.push("");

        for (const [key, currentValue] of entries) {
          if (
            currentValue === undefined ||
            currentValue === null ||
            currentValue === ""
          ) {
            // Skip unconfigured values — add to checklist
            checklistItems.push(`Set ${key}`);
            lines.push(`# ${key}=`);
            continue;
          }

          const exampleDef = (examples as EnvExample[]).find(
            (e) => e.key === key,
          );
          const sensitive = ExportEnvRepository.isSensitiveKey(
            key,
            exampleDef?.sensitive,
          );

          if (exampleDef?.comment) {
            lines.push(`# ${exampleDef.comment}`);
          }

          // Get the raw value from .env file (may be encrypted)
          const rawValue = rawEnvMap.get(key);
          let plainValue: string;

          if (rawValue !== undefined && isEncryptedValue(rawValue)) {
            // Decrypt for prod export
            const decrypted = decryptEnvValue(rawValue, cryptoKey);
            if (decrypted === null) {
              logger.warn(`Could not decrypt ${key} — including placeholder`);
              lines.push(`# WARNING: Could not decrypt — re-enter this value`);
              lines.push(`${key}=REPLACE_ME`);
              checklistItems.push(`Re-enter ${key} (decryption failed)`);
              lines.push("");
              continue;
            }
            plainValue = decrypted;
          } else {
            plainValue = String(currentValue);
          }

          // Escape values with special chars
          const needsQuotes =
            plainValue.includes(" ") ||
            plainValue.includes("#") ||
            plainValue.includes("=");

          const formattedValue = needsQuotes ? `"${plainValue}"` : plainValue;

          lines.push(`${key}=${formattedValue}`);

          if (sensitive) {
            checklistItems.push(`Verify ${key} is correct for production`);
          }

          lines.push("");
        }
      }

      // Deployment checklist
      lines.push(
        "# ============================================================",
      );
      lines.push("# DEPLOYMENT CHECKLIST");
      lines.push(
        "# ============================================================",
      );
      if (checklistItems.length === 0) {
        lines.push("# [ ] All fields configured — review values above");
      } else {
        for (const item of checklistItems) {
          lines.push(`# [ ] ${item}`);
        }
      }
      lines.push("# [ ] Changed VIBE_ADMIN_USER_PASSWORD from default value");
      lines.push("# [ ] Set NEXT_PUBLIC_APP_URL to your production domain");
      lines.push("# [ ] Verified DATABASE_URL points to production database");
      lines.push(
        "# ============================================================",
      );

      const content = lines.join("\n");

      return success({
        content,
        filename: ".env.prod",
      });
    } catch (error) {
      logger.error("Failed to export env", parseError(error));
      return fail({
        message: t("get.errors.server.title"),
        errorType: ErrorResponseTypes.INTERNAL_ERROR,
      });
    }
  }
}
