/**
 * AUTO-GENERATED FILE - DO NOT EDIT - CLIENT-SAFE
 * Generated by generators/email-templates
 *
 * Templates found: 18
 * Client-safe: No server-only imports
 */

"use client";

import type { TemplateCachedMetadata } from "@/app/api/[locale]/messenger/registry/template";

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {

};

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}
