/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/email-templates
 *
 * Templates found: 18
 */

import type { CountryLanguage } from "@/i18n/core/config";

import type {
  EmailTemplateDefinitionAny,
  TemplateCachedMetadata,
  TranslatedPreviewFieldConfig,
} from "./template";

/**
 * Lazy-loaded template registry with dynamic imports
 */
const templateLoaders: Record<string, () => Promise<EmailTemplateDefinitionAny>> = {
  "admin-contact-form-notification": async () =>
    (
      await import("@/app/api/[locale]/contact/email")
    )["adminContactFormEmailTemplate"] as EmailTemplateDefinitionAny,
  "admin-signup-notification": async () =>
    (
      await import("@/app/api/[locale]/user/public/signup/email")
    )["adminSignupNotificationEmailTemplate"] as EmailTemplateDefinitionAny,
  "admin-subscription-notification": async () =>
    (
      await import("@/app/api/[locale]/subscription/email")
    )["adminSubscriptionNotificationEmailTemplate"] as EmailTemplateDefinitionAny,
  "contact-form": async () =>
    (
      await import("@/app/api/[locale]/contact/email")
    )["contactFormEmailTemplate"] as EmailTemplateDefinitionAny,
  "credits-credit-pack-admin": async () =>
    (
      await import("@/app/api/[locale]/credits/email")
    )["creditPackAdminEmailTemplate"] as EmailTemplateDefinitionAny,
  "credits-credit-pack-user": async () =>
    (
      await import("@/app/api/[locale]/credits/email")
    )["creditPackUserEmailTemplate"] as EmailTemplateDefinitionAny,
  "newsletter-subscribe-admin": async () =>
    (
      await import("@/app/api/[locale]/newsletter/subscribe/email")
    )["adminNewsletterSubscribeEmailTemplate"] as EmailTemplateDefinitionAny,
  "newsletter-unsubscribe": async () =>
    (
      await import("@/app/api/[locale]/newsletter/unsubscribe/email")
    )["newsletterUnsubscribeEmailTemplate"] as EmailTemplateDefinitionAny,
  "newsletter-unsubscribe-admin": async () =>
    (
      await import("@/app/api/[locale]/newsletter/unsubscribe/email")
    )["adminNewsletterUnsubscribeEmailTemplate"] as EmailTemplateDefinitionAny,
  "newsletter-welcome": async () =>
    (
      await import("@/app/api/[locale]/newsletter/subscribe/email")
    )["newsletterWelcomeEmailTemplate"] as EmailTemplateDefinitionAny,
  "password-reset-confirm": async () =>
    (
      await import("@/app/api/[locale]/user/public/reset-password/confirm/email")
    )["passwordResetConfirmEmailTemplate"] as EmailTemplateDefinitionAny,
  "password-reset-request": async () =>
    (
      await import("@/app/api/[locale]/user/public/reset-password/request/email")
    )["passwordResetRequestEmailTemplate"] as EmailTemplateDefinitionAny,
  "referral-payout-admin": async () =>
    (
      await import("@/app/api/[locale]/referral/payout/email")
    )["payoutAdminEmailTemplate"] as EmailTemplateDefinitionAny,
  "referral-payout-user": async () =>
    (
      await import("@/app/api/[locale]/referral/payout/email")
    )["payoutUserEmailTemplate"] as EmailTemplateDefinitionAny,
  "signup-welcome": async () =>
    (
      await import("@/app/api/[locale]/user/public/signup/email")
    )["signupWelcomeEmailTemplate"] as EmailTemplateDefinitionAny,
  "subscription-success": async () =>
    (
      await import("@/app/api/[locale]/subscription/email")
    )["subscriptionSuccessEmailTemplate"] as EmailTemplateDefinitionAny,
  "user-create-admin-notification": async () =>
    (
      await import("@/app/api/[locale]/user/public/signup/email")
    )["userCreateAdminNotificationEmailTemplate"] as EmailTemplateDefinitionAny,
  "user-create-welcome": async () =>
    (
      await import("@/app/api/[locale]/user/public/signup/email")
    )["userCreateWelcomeEmailTemplate"] as EmailTemplateDefinitionAny,
};

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 * Actual components are lazy-loaded
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {
  "admin-contact-form-notification": {
    id: "admin-contact-form-notification",
    version: "1.0.0",
    name: "emailTemplates.adminContact.meta.name",
    description: "emailTemplates.adminContact.meta.description",
    category: "emailTemplates.adminContact.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      subject: "subject.generalInquiry",
      priority: "priority.high",
      message: "I would like to know more about your subscription plans.",
      company: "Acme Corp",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "admin-signup-notification": {
    id: "admin-signup-notification",
    version: "1.0.0",
    name: "emailTemplates.adminSignup.name",
    description: "emailTemplates.adminSignup.description",
    category: "emailTemplates.adminSignup.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      userId: "example-user-id-123",
      subscribeToNewsletter: false,
    },
  },
  "admin-subscription-notification": {
    id: "admin-subscription-notification",
    version: "1.0.0",
    name: "emailTemplates.adminNotification.name",
    description: "emailTemplates.adminNotification.description",
    category: "emailTemplates.adminNotification.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      planName: "Premium Plan",
      statusName: "Active",
    },
  },
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "emailTemplates.contactForm.meta.name",
    description: "emailTemplates.contactForm.meta.description",
    category: "emailTemplates.contactForm.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "subject.helpSupport",
      priority: "priority.medium",
      message:
        "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "credits-credit-pack-admin": {
    id: "credits-credit-pack-admin",
    version: "1.0.0",
    name: "email.creditPack.admin.title",
    description: "email.creditPack.admin.preview",
    category: "email.creditPack.admin.title",
    path: "/src/app/api/[locale]/credits/email.tsx",
    exampleProps: { userEmail: "user@example.com", credits: 5000 },
  },
  "credits-credit-pack-user": {
    id: "credits-credit-pack-user",
    version: "1.0.0",
    name: "email.creditPack.user.title",
    description: "email.creditPack.user.previewText",
    category: "email.creditPack.user.title",
    path: "/src/app/api/[locale]/credits/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      credits: 5000,
      userEmail: "user@example.com",
    },
  },
  "newsletter-subscribe-admin": {
    id: "newsletter-subscribe-admin",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      subscriberEmail: "subscriber@example.com",
      subscriberName: "Max Mustermann",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-unsubscribe-admin": {
    id: "newsletter-unsubscribe-admin",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { unsubscribedEmail: "unsubscribed@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "emailTemplates.confirm.name",
    description: "emailTemplates.confirm.description",
    category: "emailTemplates.confirm.category",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      totalModelCount: 42,
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "emailTemplates.request.name",
    description: "emailTemplates.request.description",
    category: "emailTemplates.request.category",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
      totalModelCount: 42,
    },
  },
  "referral-payout-admin": {
    id: "referral-payout-admin",
    version: "1.0.0",
    name: "payout.email.admin.title",
    description: "payout.email.admin.preview",
    category: "payout.get.title",
    path: "/src/app/api/[locale]/referral/payout/email.tsx",
    exampleProps: {
      amountCents: 5000,
      currency: "CREDITS",
      walletAddress: "",
      userEmail: "user@example.com",
    },
  },
  "referral-payout-user": {
    id: "referral-payout-user",
    version: "1.0.0",
    name: "payout.email.user.titleCrypto",
    description: "payout.email.user.previewCrypto",
    category: "payout.get.title",
    path: "/src/app/api/[locale]/referral/payout/email.tsx",
    exampleProps: { amountCents: 5000, currency: "CREDITS", walletAddress: "" },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      totalModelCount: 42,
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "emailTemplates.success.name",
    description: "emailTemplates.success.description",
    category: "emailTemplates.success.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
      totalModelCount: 42,
    },
  },
  "user-create-admin-notification": {
    id: "user-create-admin-notification",
    version: "1.0.0",
    name: "emailTemplates.adminSignup.name",
    description: "emailTemplates.adminSignup.description",
    category: "emailTemplates.adminSignup.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      userId: "example-user-id-123",
      subscribeToNewsletter: false,
    },
  },
  "user-create-welcome": {
    id: "user-create-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      totalModelCount: 42,
    },
  },
};

/**
 * Get template by ID (lazy loads on first access)
 * Returns the template with its specific props type
 */
export async function getTemplate(
  id: string,
): Promise<EmailTemplateDefinitionAny | undefined> {
  const loader = templateLoaders[id];
  if (!loader) {
    return undefined;
  }

  return await loader();
}

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template IDs
 */
export function getAllTemplateIds(): string[] {
  return Object.keys(templateLoaders);
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}

/**
 * Check if template exists
 */
export function hasTemplate(id: string): boolean {
  return id in templateLoaders;
}

/**
 * Translate template metadata using the template's own scopedT.
 * Returns plain strings instead of translation keys.
 */
export async function getTranslatedTemplateMetadata(
  id: string,
  locale: CountryLanguage,
): Promise<
  | (Omit<
      TemplateCachedMetadata<string>,
      "name" | "description" | "category"
    > & {
      name: string;
      description: string;
      category: string;
    })
  | undefined
> {
  const template = await getTemplate(id);
  if (!template) {
    return undefined;
  }
  const cached = templateMetadataMap[id];
  if (!cached) {
    return undefined;
  }
  const { t } = template.scopedTranslation.scopedT(locale);
  return {
    ...cached,
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    name: t(template.meta.name as never),
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    description: t(template.meta.description as never),
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    category: t(template.meta.category as never),
  };
}

/**
 * Translate preview fields using the template's own scopedT.
 * Returns configs with plain label/description strings.
 */
export function translatePreviewFields(
  template: EmailTemplateDefinitionAny,
  locale: CountryLanguage,
): Record<string, TranslatedPreviewFieldConfig> | undefined {
  const fields = template.meta.previewFields;
  if (!fields) {
    return undefined;
  }
  const { t } = template.scopedTranslation.scopedT(locale);
  const result: Record<string, TranslatedPreviewFieldConfig> = {};
  for (const [key, field] of Object.entries(fields)) {
    result[key] = {
      ...field,
      // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
      label: t(field.label as never),
      description: field.description
        ? // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
          t(field.description as never)
        : undefined,
      options: field.options?.map((opt) => ({
        value: opt.value,
        // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
        label: t(opt.label as never),
      })),
    };
  }
  return result;
}

/**
 * Load all templates and return translated metadata for each.
 */
export async function getAllTranslatedTemplateMetadata(
  locale: CountryLanguage,
): Promise<
  Array<
    Omit<
      TemplateCachedMetadata<string>,
      "name" | "description" | "category"
    > & {
      name: string;
      description: string;
      category: string;
    }
  >
> {
  const ids = getAllTemplateIds();
  const results = await Promise.all(
    ids.map((id) => getTranslatedTemplateMetadata(id, locale)),
  );
  return results.filter((r): r is NonNullable<typeof r> => r !== undefined);
}
