/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/email-templates
 *
 * Templates found: 0
 */

import type { CountryLanguage } from "next-vibe/core/i18n/core/config";

import type { EmailTemplateDefinitionAny, TemplateCachedMetadata, TranslatedPreviewFieldConfig } from "@/app/api/[locale]/messenger/registry/template";

/**
 * Lazy-loaded template registry with dynamic imports
 */
const templateLoaders: Record<string, () => Promise<EmailTemplateDefinitionAny>> = {

};

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 * Actual components are lazy-loaded
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {

};

/**
 * Get template by ID (lazy loads on first access)
 * Returns the template with its specific props type
 */
export async function getTemplate(
  id: string,
): Promise<EmailTemplateDefinitionAny | undefined> {
  const loader = templateLoaders[id];
  if (!loader) {
    return undefined;
  }

  return await loader();
}

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template IDs
 */
export function getAllTemplateIds(): string[] {
  return Object.keys(templateLoaders);
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}

/**
 * Check if template exists
 */
export function hasTemplate(id: string): boolean {
  return id in templateLoaders;
}

/**
 * Translate template metadata using the template's own scopedT.
 * Returns plain strings instead of translation keys.
 */
export async function getTranslatedTemplateMetadata(
  id: string,
  locale: CountryLanguage,
): Promise<
  | (Omit<
      TemplateCachedMetadata<string>,
      "name" | "description" | "category"
    > & {
      name: string;
      description: string;
      category: string;
    })
  | undefined
> {
  const template = await getTemplate(id);
  if (!template) {
    return undefined;
  }
  const cached = templateMetadataMap[id];
  if (!cached) {
    return undefined;
  }
  const { t } = template.scopedTranslation.scopedT(locale);
  return {
    ...cached,
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    name: t(template.meta.name as never),
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    description: t(template.meta.description as never),
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
    category: t(template.meta.category as never),
  };
}

/**
 * Translate preview fields using the template's own scopedT.
 * Returns configs with plain label/description strings.
 */
export function translatePreviewFields(
  template: EmailTemplateDefinitionAny,
  locale: CountryLanguage,
): Record<string, TranslatedPreviewFieldConfig> | undefined {
  const fields = template.meta.previewFields;
  if (!fields) {
    return undefined;
  }
  const { t } = template.scopedTranslation.scopedT(locale);
  const result: Record<string, TranslatedPreviewFieldConfig> = {};
  for (const [key, field] of Object.entries(fields)) {
    result[key] = {
      ...field,
      // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
      label: t(field.label as never),
      description: field.description
        ? // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
          t(field.description as never)
        : undefined,
      options: field.options?.map((opt) => ({
        value: opt.value,
        // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: keys come from the same template's own translation scope
        label: t(opt.label as never),
      })),
    };
  }
  return result;
}

/**
 * Load all templates and return translated metadata for each.
 */
export async function getAllTranslatedTemplateMetadata(
  locale: CountryLanguage,
): Promise<
  Array<
    Omit<
      TemplateCachedMetadata<string>,
      "name" | "description" | "category"
    > & {
      name: string;
      description: string;
      category: string;
    }
  >
> {
  const ids = getAllTemplateIds();
  const results = await Promise.all(
    ids.map((id) => getTranslatedTemplateMetadata(id, locale)),
  );
  return results.filter((r): r is NonNullable<typeof r> => r !== undefined);
}
