/**
 * AUTO-GENERATED FILE - DO NOT EDIT - CLIENT-SAFE
 * Generated by generators/email-templates
 *
 * Templates found: 18
 * Client-safe: No server-only imports
 */

"use client";

import type { TemplateCachedMetadata } from "./template";

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {
  "admin-contact-form-notification": {
    id: "admin-contact-form-notification",
    version: "1.0.0",
    name: "emailTemplates.adminContact.meta.name",
    description: "emailTemplates.adminContact.meta.description",
    category: "emailTemplates.adminContact.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      subject: "subject.generalInquiry",
      priority: "priority.high",
      message: "I would like to know more about your subscription plans.",
      company: "Acme Corp",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "admin-signup-notification": {
    id: "admin-signup-notification",
    version: "1.0.0",
    name: "emailTemplates.adminSignup.name",
    description: "emailTemplates.adminSignup.description",
    category: "emailTemplates.adminSignup.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      userId: "example-user-id-123",
      subscribeToNewsletter: false,
    },
  },
  "admin-subscription-notification": {
    id: "admin-subscription-notification",
    version: "1.0.0",
    name: "emailTemplates.adminNotification.name",
    description: "emailTemplates.adminNotification.description",
    category: "emailTemplates.adminNotification.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      planName: "Premium Plan",
      statusName: "Active",
    },
  },
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "emailTemplates.contactForm.meta.name",
    description: "emailTemplates.contactForm.meta.description",
    category: "emailTemplates.contactForm.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "subject.helpSupport",
      priority: "priority.medium",
      message:
        "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "credits-credit-pack-admin": {
    id: "credits-credit-pack-admin",
    version: "1.0.0",
    name: "email.creditPack.admin.title",
    description: "email.creditPack.admin.preview",
    category: "email.creditPack.admin.title",
    path: "/src/app/api/[locale]/credits/email.tsx",
    exampleProps: { userEmail: "user@example.com", credits: 5000 },
  },
  "credits-credit-pack-user": {
    id: "credits-credit-pack-user",
    version: "1.0.0",
    name: "email.creditPack.user.title",
    description: "email.creditPack.user.previewText",
    category: "email.creditPack.user.title",
    path: "/src/app/api/[locale]/credits/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      credits: 5000,
      userEmail: "user@example.com",
    },
  },
  "newsletter-subscribe-admin": {
    id: "newsletter-subscribe-admin",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      subscriberEmail: "subscriber@example.com",
      subscriberName: "Max Mustermann",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-unsubscribe-admin": {
    id: "newsletter-unsubscribe-admin",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { unsubscribedEmail: "unsubscribed@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "emailTemplates.confirm.name",
    description: "emailTemplates.confirm.description",
    category: "emailTemplates.confirm.category",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "emailTemplates.request.name",
    description: "emailTemplates.request.description",
    category: "emailTemplates.request.category",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
    },
  },
  "referral-payout-admin": {
    id: "referral-payout-admin",
    version: "1.0.0",
    name: "payout.email.admin.title",
    description: "payout.email.admin.preview",
    category: "payout.get.title",
    path: "/src/app/api/[locale]/referral/payout/email.tsx",
    exampleProps: {
      amountCents: 5000,
      currency: "CREDITS",
      walletAddress: "",
      userEmail: "user@example.com",
    },
  },
  "referral-payout-user": {
    id: "referral-payout-user",
    version: "1.0.0",
    name: "payout.email.user.titleCrypto",
    description: "payout.email.user.previewCrypto",
    category: "payout.get.title",
    path: "/src/app/api/[locale]/referral/payout/email.tsx",
    exampleProps: { amountCents: 5000, currency: "CREDITS", walletAddress: "" },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "emailTemplates.success.name",
    description: "emailTemplates.success.description",
    category: "emailTemplates.success.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
    },
  },
  "user-create-admin-notification": {
    id: "user-create-admin-notification",
    version: "1.0.0",
    name: "emailTemplates.adminSignup.name",
    description: "emailTemplates.adminSignup.description",
    category: "emailTemplates.adminSignup.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      publicName: "Max Mustermann",
      email: "max@example.com",
      userId: "example-user-id-123",
      subscribeToNewsletter: false,
    },
  },
  "user-create-welcome": {
    id: "user-create-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
};

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}
