/**
 * AUTO-GENERATED FILE - DO NOT EDIT - CLIENT-SAFE
 * Generated by generators/email-templates
 *
 * Templates found: 7
 * Client-safe: No server-only imports
 */

"use client";

import type { TemplateCachedMetadata } from "./template";

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "emailTemplates.contactForm.meta.name",
    description: "emailTemplates.contactForm.meta.description",
    category: "emailTemplates.contactForm.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "subject.helpSupport",
      priority: "priority.medium",
      message:
        "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "emailTemplates.confirm.name",
    description: "emailTemplates.confirm.description",
    category: "emailTemplates.confirm.category",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "emailTemplates.request.name",
    description: "emailTemplates.request.description",
    category: "emailTemplates.request.category",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
    },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "emailTemplates.success.name",
    description: "emailTemplates.success.description",
    category: "emailTemplates.success.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
    },
  },
};

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}
