/**
 * Cortex Seeds Embeddings Generator (domain-co-located).
 *
 * Pre-computes embeddings for all cortex seed items at `vibe gen` time, writing each
 * to a sibling .embedding.ts (dynamic templates → dynamic.embedding.ts). Hash-gated.
 * Byte-identical to the former tooling/generators/cortex-templates. Scans its own
 * seeds dir (cortex-specific, not a shared file list).
 */

import "server-only";

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { GeneratorDefinition } from "next-vibe/core/generators/shared/shared-inputs";

import { getSrcDir } from "@/env/paths";

/** Recursively find all seed .ts files, excluding embedding/index/types. */
function scanSeedFiles(dir: string): string[] {
  const results: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...scanSeedFiles(fullPath));
    } else if (
      entry.isFile() &&
      entry.name.endsWith(".ts") &&
      !entry.name.endsWith(".embedding.ts") &&
      entry.name !== "index.ts" &&
      entry.name !== "types.ts"
    ) {
      results.push(fullPath);
    }
  }
  return results.toSorted();
}

function readFileSafe(path: string): string {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return "";
  }
}

function extractHash(fileContent: string): string | null {
  const match = /embeddingHash:\s*["']([a-f0-9]+)["']/.exec(fileContent);
  return match?.[1] ?? null;
}

function buildSeedEmbeddingFile(
  path: string,
  hash: string,
  embeddingStr: string,
  typesImportPath: string,
): string {
  return `import type { CortexSeedEmbedding } from "${typesImportPath}";

/** Generated by \`vibe gen\` - do not edit manually */
export const embedding: CortexSeedEmbedding = {
  path: "${path}",
  embeddingHash: "${hash}",
  // prettier-ignore
  embedding: ${embeddingStr},
};
`;
}

function buildDynamicEmbeddingsFile(
  entries: Array<{ id: string; path: string; hash: string; embedding: string }>,
): string {
  const items = entries
    .map(
      (e) =>
        `  {\n    id: "${e.id}",\n    path: "${e.path}",\n    embeddingHash: "${e.hash}",\n    // prettier-ignore\n    embedding: ${e.embedding},\n  }`,
    )
    .join(",\n");

  return `import type { CortexSeedEmbedding } from "next-vibe/agent/cortex/seeds/types";

/** Generated by \`vibe gen\` - do not edit manually.
 * Embeddings for dynamic templates (i18n-generated, no physical seed file). */
export const dynamicEmbeddings: (CortexSeedEmbedding & { id: string })[] = [
${items},
];
`;
}

export const generator: GeneratorDefinition = {
  key: "cortex",
  phase: "default",
  needs: {},
  cacheKey: "cortex-seeds",
  findInputs() {
    return scanSeedFiles(join(getSrcDir(), "vibe", "agent", "cortex", "seeds"));
  },
  /** Generate cortex seed embeddings. Scans cortex/seeds; writes sibling files. */
  async generate(ctx) {
    const { logger } = ctx;

    const { computeEmbeddingHash } =
      await import("next-vibe/agent/cortex/embeddings/service");
    const { getAllTemplates } =
      await import("next-vibe/agent/cortex/seeds/templates");
    const { defaultLocale } = await import("next-vibe/core/i18n/core/config");
    const ALL_SEEDS = getAllTemplates(defaultLocale).map((item) => ({ item }));

    const seedsDir = join(getSrcDir(), "vibe", "agent", "cortex", "seeds");
    const seedFiles = scanSeedFiles(seedsDir);

    const idToSeedFile = new Map<string, string>();
    for (const filePath of seedFiles) {
      const content = readFileSync(filePath, "utf-8");
      const idMatch = /id:\s*["']([^"']+)["']/.exec(content);
      if (idMatch) {
        idToSeedFile.set(idMatch[1], filePath);
      }
    }

    const dynamicEmbeddingsFile = join(seedsDir, "dynamic.embedding.ts");
    const existingDynamic = readFileSafe(dynamicEmbeddingsFile);

    // Pass 1: hash-check only — no API calls, no heavy imports.
    interface WorkItem {
      item: (typeof ALL_SEEDS)[number]["item"];
      seedFile: string | undefined;
      hash: string;
      embeddingFile: string;
    }
    const needsWork: WorkItem[] = [];
    let skipped = 0;

    for (const { item } of ALL_SEEDS) {
      const seedFile = idToSeedFile.get(item.id);
      const hash = computeEmbeddingHash(item.path, item.content);

      if (seedFile) {
        const embeddingFile = seedFile.replace(/\.ts$/, ".embedding.ts");
        const existingHash = extractHash(readFileSafe(embeddingFile));
        if (existingHash === hash) {
          skipped++;
        } else {
          needsWork.push({ item, seedFile, hash, embeddingFile });
        }
      } else {
        if (existingDynamic.includes(`"${hash}"`)) {
          skipped++;
        } else {
          needsWork.push({
            item,
            seedFile: undefined,
            hash,
            embeddingFile: "",
          });
        }
      }
    }

    const total = ALL_SEEDS.length;

    // Early exit when everything is cached — no API, no context setup.
    if (needsWork.length === 0) {
      return {
        summary: `cortex embeddings (${total} seeds, 0 embedded, ${skipped} cached)`,
        counts: { seeds: total, embedded: 0, cached: skipped },
      };
    }

    // Pass 2: heavy imports only if there's actual work.
    const { generateEmbedding } =
      await import("next-vibe/agent/cortex/embeddings/service");
    const { makeHeadlessContext } = await import("next-vibe/agent/chat/config");
    const rootCtx = makeHeadlessContext(undefined, undefined, "UTC");

    let generated = 0;
    const dynamicEmbeddings: Array<{
      id: string;
      path: string;
      hash: string;
      embedding: string;
    }> = [];

    for (const { item, seedFile, hash, embeddingFile } of needsWork) {
      const textToEmbed = `${item.path}\n\n${item.content}`;
      const embedding = await generateEmbedding(textToEmbed, rootCtx);
      if (!embedding) {
        logger.warn(`  skipped (API unavailable): ${item.id}`);
        skipped++;
        continue;
      }

      const embeddingStr = `[${embedding.map((v) => Number(v.toPrecision(15))).join(",")}]`;

      if (seedFile) {
        const relPath = embeddingFile.replace(`${seedsDir}/`, "");
        const depth = relPath.split("/").length - 1;
        const relPrefix = "../".repeat(depth);
        writeFileSync(
          embeddingFile,
          buildSeedEmbeddingFile(
            item.path,
            hash,
            embeddingStr,
            `${relPrefix}types`,
          ),
          "utf-8",
        );
        logger.debug(`  embedded: ${item.id}`);
      } else {
        dynamicEmbeddings.push({
          id: item.id,
          path: item.path,
          hash,
          embedding: embeddingStr,
        });
        logger.debug(`  embedded (dynamic): ${item.id}`);
      }
      generated++;
    }

    if (dynamicEmbeddings.length > 0) {
      writeFileSync(
        dynamicEmbeddingsFile,
        buildDynamicEmbeddingsFile(dynamicEmbeddings),
        "utf-8",
      );
    }

    return {
      summary: `cortex embeddings (${total} seeds, ${generated} embedded, ${skipped} cached)`,
      counts: { seeds: total, embedded: generated, cached: skipped },
    };
  },
};
