/**
 * Agent Docs Generator
 *
 * Generates CLAUDE.md and AGENTS.md from the vibe-coder skill's systemPrompt.
 * The skill is the single source of truth for project instructions.
 *
 * Tokens replaced:
 *   {{AGENT_NAME}}      → "Claude Code" or "Coding Agent"
 *   {{AGENT_DOCS_FILE}} → "CLAUDE.md" or "AGENTS.md"
 */

import "server-only";

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import { parseError } from "next-vibe/shared/utils/parse-error";

import type { EndpointLogger } from "@/app/api/[locale]/system/unified-interface/shared/logger/endpoint";
import {
  formatDuration,
  formatGenerator,
} from "@/app/api/[locale]/system/unified-interface/shared/logger/formatters";

interface AgentDocsResult {
  success: boolean;
  message?: string;
  filesWritten: number;
  duration: number;
}

interface AgentDocTarget {
  fileName: string;
  agentName: string;
}

const TARGETS: AgentDocTarget[] = [
  { fileName: "CLAUDE.md", agentName: "Claude Code" },
  { fileName: "AGENTS.md", agentName: "Coding Agent" },
];

const HEADER =
  "<!-- AUTO-GENERATED by vibe gen from vibe-coder skill.ts. Do not edit manually. -->\n\n";

export class AgentDocsGeneratorRepository {
  static async generateAgentDocs(
    logger: EndpointLogger,
  ): Promise<AgentDocsResult> {
    const startTime = Date.now();

    try {
      // Import the source-of-truth prompt
      const { PROJECT_INSTRUCTIONS } =
        await import("@/app/api/[locale]/agent/chat/skills/default-skills/vibe-coder/skill");

      const projectRoot = process.cwd();
      let filesWritten = 0;

      for (const target of TARGETS) {
        const content =
          HEADER +
          PROJECT_INSTRUCTIONS.replaceAll(
            "{{AGENT_NAME}}",
            target.agentName,
          ).replaceAll("{{AGENT_DOCS_FILE}}", target.fileName);

        const outputPath = join(projectRoot, target.fileName);
        await writeFile(outputPath, content, "utf-8");
        filesWritten++;

        logger.debug(`Wrote ${target.fileName}`);
      }

      const duration = Date.now() - startTime;

      logger.info(
        formatGenerator(
          `Generated ${filesWritten} agent docs in ${formatDuration(duration)}`,
          "📝",
        ),
      );

      return {
        success: true,
        filesWritten,
        duration,
      };
    } catch (error) {
      const duration = Date.now() - startTime;
      logger.error("Agent docs generation failed", {
        error: parseError(error),
      });
      return {
        success: false,
        message: `Agent docs generation failed: ${parseError(error).message}`,
        filesWritten: 0,
        duration,
      };
    }
  }
}
