import type { TranslationKey } from "@/i18n/core/static-types";

import type { IconKey, IconValue } from "../config/icons";
import type { ModelId } from "../config/models";

/**
 * Message role types
 */
export type MessageRole = "assistant" | "user" | "system" | "error";

/**
 * User information for multi-user support
 */
export interface MessageAuthor {
  /** User ID (for multi-user) or "local" for local user */
  id: string;
  /** Display name */
  name: string;
  /** Avatar URL or identifier */
  avatar?: string;
  /** User color for visual distinction */
  color?: string;
  /** Whether this is an AI model */
  isAI?: boolean;
  /** Model ID if this is an AI */
  modelId?: ModelId;
}

/**
 * Base message structure shared by all message types
 */
interface BaseMessage {
  /** Unique identifier for this message */
  id: string;
  /** Message content */
  content: string;
  /** Timestamp when message was created */
  timestamp: number;
  /** ID of the parent message (null for root messages) */
  parentId: string | null;
  /** Array of child message IDs (branches from this message) */
  childrenIds: string[];
  /** Author information (for multi-user support) */
  author?: MessageAuthor;
  /** Metadata for additional information */
  metadata?: {
    /** Whether this message was edited */
    edited?: boolean;
    /** Original message ID if this is an edit */
    originalId?: string;
    /** Number of tokens in the message */
    tokens?: number;
    /** Reply count (number of direct children) */
    replyCount?: number;
    /** Whether this message is collapsed in thread view */
    collapsed?: boolean;
    /** Depth in thread (0 = root, 1 = first reply, etc.) */
    depth?: number;
    /** User vote on this message (1 = upvote, -1 = downvote, 0 or undefined = no vote) */
    userVote?: number;
    /** Total vote score (sum of all votes) */
    voteScore?: number;
  };
}

/**
 * User message - sent by the user
 */
export interface UserMessage extends BaseMessage {
  role: "user";
  /** Persona/tone used for this message */
  tone?: string;
}

/**
 * Assistant message - generated by AI
 */
export interface AssistantMessage extends BaseMessage {
  role: "assistant";
  /** Model used to generate this message */
  model?: ModelId;
  /** Persona/tone used for this message */
  tone?: string;
}

/**
 * System message - system notifications
 */
export interface SystemMessage extends BaseMessage {
  role: "system";
}

/**
 * Error message - error notifications
 */
export interface ErrorMessage extends BaseMessage {
  role: "error";
  /** Error details */
  error?: {
    type: string;
    message: string;
    code?: string;
  };
}

/**
 * Discriminated union of all message types
 * Use this for type-safe message handling
 */
export type ChatMessage =
  | UserMessage
  | AssistantMessage
  | SystemMessage
  | ErrorMessage;

/**
 * Represents a path through the conversation tree
 * Used to track which branch is currently active at each level
 */
export interface ConversationPath {
  /** Array of message IDs representing the current path from root to leaf */
  messageIds: string[];

  /** Index of the currently selected branch at each branching point */
  branchIndices: Record<string, number>;
}

/**
 * Thread metadata and configuration
 */
export interface ChatThread {
  /** Unique identifier for this thread */
  id: string;

  /** Thread title (auto-generated or user-defined) */
  title: string;

  /** Folder ID this thread belongs to */
  folderId: string | null;

  /** Timestamp when thread was created */
  createdAt: number;

  /** Timestamp when thread was last updated */
  updatedAt: number;

  /** All messages in this thread (flat map for easy lookup) */
  messages: Record<string, ChatMessage>;

  /** ID of the root message (null if no root/welcome message) */
  rootMessageId: string | null;

  /** Current active conversation path */
  currentPath: ConversationPath;

  /** Thread settings */
  settings?: {
    /** Default model for this thread */
    defaultModel?: ModelId;
    /** Default persona for this thread */
    defaultTone?: string;
    /** Custom system prompt for this thread */
    systemPrompt?: string;
  };

  /** Thread metadata */
  metadata?: {
    /** Whether thread is pinned */
    pinned?: boolean;
    /** Whether thread is archived */
    archived?: boolean;
    /** Tags for organization */
    tags?: string[];
    /** Preview text (first user message) */
    preview?: string;
  };
}

/**
 * Folder structure for organizing threads
 */
export interface ChatFolder {
  /** Unique identifier for this folder */
  id: string;

  /** Folder name (can be user-customized or translation key) */
  name: string;

  /** Translation key for default folders (e.g., "app.chat.common.privateChats") */
  translationKey?: TranslationKey;

  /** Whether the user has customized the folder name (overrides translation) */
  isUserCustomized?: boolean;

  /** Folder icon (emoji, icon key, or React component) */
  icon?: IconValue;

  /** URL path segment for this folder (e.g., "private", "shared", "public", "incognito") */
  urlPath?: string;

  /** Parent folder ID (null for root folders) */
  parentId: string | null;

  /** Child folder IDs */
  childrenIds: string[];

  /** Timestamp when folder was created */
  createdAt: number;

  /** Timestamp when folder was last updated */
  updatedAt: number;

  /** Folder color for visual distinction */
  color?: string;

  /** Whether folder is expanded in UI */
  expanded?: boolean;
}

/**
 * Complete chat state including all threads and folders
 */
export interface ChatState {
  /** All threads indexed by ID */
  threads: Record<string, ChatThread>;

  /** All folders indexed by ID */
  folders: Record<string, ChatFolder>;

  /** ID of the currently active thread */
  activeThreadId: string | null;

  /** Root folder IDs (top-level folders) */
  rootFolderIds: string[];

  /** Threads not in any folder */
  unfiledThreadIds: string[];

  /** Last updated timestamp */
  lastUpdated: number;

  /** Version for migration purposes */
  version: number;
}

/**
 * Helper type for creating new messages
 * More flexible than the discriminated union for message creation
 */
export interface NewMessageInput {
  id?: string;
  role: MessageRole;
  content: string;
  timestamp?: number;
  parentId: string | null;
  childrenIds?: string[];
  author?: MessageAuthor;
  model?: ModelId;
  tone?: string;
  error?: {
    type: string;
    message: string;
    code?: string;
  };
  metadata?: {
    edited?: boolean;
    originalId?: string;
    tokens?: number;
    replyCount?: number;
    collapsed?: boolean;
    depth?: number;
    userVote?: number;
    voteScore?: number;
  };
}

/**
 * Helper type for creating new threads
 */
export type NewThreadInput = Omit<
  ChatThread,
  | "id"
  | "createdAt"
  | "updatedAt"
  | "messages"
  | "rootMessageId"
  | "currentPath"
> & {
  id?: string;
  createdAt?: number;
  updatedAt?: number;
};

/**
 * Helper type for creating new folders
 */
export type NewFolderInput = Omit<
  ChatFolder,
  "id" | "createdAt" | "updatedAt" | "childrenIds"
> & {
  id?: string;
  createdAt?: number;
  updatedAt?: number;
  childrenIds?: string[];
};

/**
 * Storage keys for localStorage
 */
export const STORAGE_KEYS = {
  CHAT_STATE: "chat-state-v2",
  ACTIVE_THREAD: "chat-active-thread",
  UI_PREFERENCES: "chat-ui-preferences",
} as const;

/**
 * Default folder IDs
 */
export const DEFAULT_FOLDERS = {
  PRIVATE: "general",
  SHARED: "shared",
  PUBLIC: "public",
  INCOGNITO: "incognito",
} as const;

/**
 * Default folder configuration with all metadata
 */
export const DEFAULT_FOLDER_CONFIGS: {
  id: (typeof DEFAULT_FOLDERS)[keyof typeof DEFAULT_FOLDERS];
  translationKey: TranslationKey;
  icon: IconKey;
  descriptionKey: TranslationKey;
  order: number;
  color: string;
}[] = [
  {
    id: DEFAULT_FOLDERS.PRIVATE,
    translationKey: "app.chat.common.privateChats" as const,
    icon: "lock" as const,
    descriptionKey: "app.chat.folders.privateDescription" as const,
    order: 0,
    color: "sky", // Softer blue for private/secure
  },
  {
    id: DEFAULT_FOLDERS.INCOGNITO,
    translationKey: "app.chat.common.incognitoChats" as const,
    icon: "shield-plus" as const,
    descriptionKey: "app.chat.folders.incognitoDescription" as const,
    order: 1,
    color: "zinc", // Neutral gray for incognito/hidden
  },
  {
    id: DEFAULT_FOLDERS.SHARED,
    translationKey: "app.chat.common.sharedChats" as const,
    icon: "users" as const,
    descriptionKey: "app.chat.folders.sharedDescription" as const,
    order: 2,
    color: "teal", // Collaborative teal for shared
  },
  {
    id: DEFAULT_FOLDERS.PUBLIC,
    translationKey: "app.chat.common.publicChats" as const,
    icon: "1a" as const,
    descriptionKey: "app.chat.folders.publicDescription" as const,
    order: 3,
    color: "amber", // Premium gold/amber for public 1A
  },
] as const;

/**
 * Check if a folder is a default folder (cannot be deleted or moved)
 */
export function isDefaultFolder(folderId: string): boolean {
  return Object.values(DEFAULT_FOLDERS).includes(
    folderId as (typeof DEFAULT_FOLDERS)[keyof typeof DEFAULT_FOLDERS],
  );
}

/**
 * Get the icon for a folder
 * For default folders, always use the icon from DEFAULT_FOLDER_CONFIGS
 * For custom folders, use the stored icon or fallback to "folder"
 */
export function getFolderIcon(folder: ChatFolder): IconValue {
  if (isDefaultFolder(folder.id)) {
    const config = DEFAULT_FOLDER_CONFIGS.find((c) => c.id === folder.id);
    return config?.icon || "folder";
  }
  return folder.icon || "folder";
}

/**
 * Get the color for a folder
 * For default folders, always use the color from DEFAULT_FOLDER_CONFIGS
 * For custom folders, return null (no special color)
 */
export function getFolderColor(folderId: string): string | null {
  if (isDefaultFolder(folderId)) {
    const config = DEFAULT_FOLDER_CONFIGS.find((c) => c.id === folderId);
    return config?.color || null;
  }
  return null;
}

/**
 * Get the count of direct children (threads + subfolders) in a folder
 * Does NOT count nested items recursively
 */
export function getDirectChildrenCount(
  state: ChatState,
  folderId: string,
): number {
  // Count direct threads
  const directThreads = Object.values(state.threads).filter(
    (thread) => thread.folderId === folderId,
  ).length;

  // Count direct subfolders
  const directSubfolders = Object.values(state.folders).filter(
    (folder) => folder.parentId === folderId,
  ).length;

  return directThreads + directSubfolders;
}

/**
 * View mode for messages
 */
export type ViewMode = "linear" | "threaded" | "flat";

/**
 * UI preferences for chat interface
 */
export interface ChatUIPreferences {
  /** Whether sidebar is collapsed */
  sidebarCollapsed: boolean;

  /** Sidebar width in pixels */
  sidebarWidth: number;

  /** Whether to show message timestamps */
  showTimestamps: boolean;

  /** Whether to show branch indicators */
  showBranchIndicators: boolean;

  /** View mode for messages */
  viewMode: ViewMode;

  /** Theme preference */
  theme?: "light" | "dark" | "system";

  /** Font size preference */
  fontSize?: "small" | "medium" | "large";
}
