import type { ModelId } from "../config/models";

/**
 * Message role types
 */
export type MessageRole = "assistant" | "user" | "system" | "error";

/**
 * User information for multi-user support
 */
export interface MessageAuthor {
  /** User ID (for multi-user) or "local" for local user */
  id: string;
  /** Display name */
  name: string;
  /** Avatar URL or identifier */
  avatar?: string;
  /** User color for visual distinction */
  color?: string;
  /** Whether this is an AI model */
  isAI?: boolean;
  /** Model ID if this is an AI */
  modelId?: ModelId;
}

/**
 * Base message structure shared by all message types
 */
interface BaseMessage {
  /** Unique identifier for this message */
  id: string;
  /** Message content */
  content: string;
  /** Timestamp when message was created */
  timestamp: number;
  /** ID of the parent message (null for root messages) */
  parentId: string | null;
  /** Array of child message IDs (branches from this message) */
  childrenIds: string[];
  /** Author information (for multi-user support) */
  author?: MessageAuthor;
  /** Metadata for additional information */
  metadata?: {
    /** Whether this message was edited */
    edited?: boolean;
    /** Original message ID if this is an edit */
    originalId?: string;
    /** Number of tokens in the message */
    tokens?: number;
    /** Reply count (number of direct children) */
    replyCount?: number;
    /** Whether this message is collapsed in thread view */
    collapsed?: boolean;
    /** Depth in thread (0 = root, 1 = first reply, etc.) */
    depth?: number;
  };
}

/**
 * User message - sent by the user
 */
export interface UserMessage extends BaseMessage {
  role: "user";
  /** Persona/tone used for this message */
  tone?: string;
}

/**
 * Assistant message - generated by AI
 */
export interface AssistantMessage extends BaseMessage {
  role: "assistant";
  /** Model used to generate this message */
  model?: ModelId;
  /** Persona/tone used for this message */
  tone?: string;
}

/**
 * System message - system notifications
 */
export interface SystemMessage extends BaseMessage {
  role: "system";
}

/**
 * Error message - error notifications
 */
export interface ErrorMessage extends BaseMessage {
  role: "error";
  /** Error details */
  error?: {
    type: string;
    message: string;
    code?: string;
  };
}

/**
 * Discriminated union of all message types
 * Use this for type-safe message handling
 */
export type ChatMessage =
  | UserMessage
  | AssistantMessage
  | SystemMessage
  | ErrorMessage;

/**
 * Represents a path through the conversation tree
 * Used to track which branch is currently active at each level
 */
export interface ConversationPath {
  /** Array of message IDs representing the current path from root to leaf */
  messageIds: string[];

  /** Index of the currently selected branch at each branching point */
  branchIndices: Record<string, number>;
}

/**
 * Thread metadata and configuration
 */
export interface ChatThread {
  /** Unique identifier for this thread */
  id: string;

  /** Thread title (auto-generated or user-defined) */
  title: string;

  /** Folder ID this thread belongs to */
  folderId: string | null;

  /** Timestamp when thread was created */
  createdAt: number;

  /** Timestamp when thread was last updated */
  updatedAt: number;

  /** All messages in this thread (flat map for easy lookup) */
  messages: Record<string, ChatMessage>;

  /** ID of the root message (null if no root/welcome message) */
  rootMessageId: string | null;

  /** Current active conversation path */
  currentPath: ConversationPath;

  /** Thread settings */
  settings?: {
    /** Default model for this thread */
    defaultModel?: ModelId;
    /** Default persona for this thread */
    defaultTone?: string;
    /** Custom system prompt for this thread */
    systemPrompt?: string;
  };

  /** Thread metadata */
  metadata?: {
    /** Whether thread is pinned */
    pinned?: boolean;
    /** Whether thread is archived */
    archived?: boolean;
    /** Tags for organization */
    tags?: string[];
    /** Preview text (first user message) */
    preview?: string;
  };
}

/**
 * Folder structure for organizing threads
 */
export interface ChatFolder {
  /** Unique identifier for this folder */
  id: string;

  /** Folder name */
  name: string;

  /** Folder icon (lucide icon name or si icon name) */
  icon?: string;

  /** Parent folder ID (null for root folders) */
  parentId: string | null;

  /** Child folder IDs */
  childrenIds: string[];

  /** Timestamp when folder was created */
  createdAt: number;

  /** Timestamp when folder was last updated */
  updatedAt: number;

  /** Folder color for visual distinction */
  color?: string;

  /** Whether folder is expanded in UI */
  expanded?: boolean;
}

/**
 * Complete chat state including all threads and folders
 */
export interface ChatState {
  /** All threads indexed by ID */
  threads: Record<string, ChatThread>;

  /** All folders indexed by ID */
  folders: Record<string, ChatFolder>;

  /** ID of the currently active thread */
  activeThreadId: string | null;

  /** Root folder IDs (top-level folders) */
  rootFolderIds: string[];

  /** Threads not in any folder */
  unfiledThreadIds: string[];

  /** Last updated timestamp */
  lastUpdated: number;

  /** Version for migration purposes */
  version: number;
}

/**
 * Helper type for creating new messages
 * More flexible than the discriminated union for message creation
 */
export interface NewMessageInput {
  id?: string;
  role: MessageRole;
  content: string;
  timestamp?: number;
  parentId: string | null;
  childrenIds?: string[];
  author?: MessageAuthor;
  model?: ModelId;
  tone?: string;
  error?: {
    type: string;
    message: string;
    code?: string;
  };
  metadata?: {
    edited?: boolean;
    originalId?: string;
    tokens?: number;
    replyCount?: number;
    collapsed?: boolean;
    depth?: number;
  };
}

/**
 * Helper type for creating new threads
 */
export type NewThreadInput = Omit<
  ChatThread,
  | "id"
  | "createdAt"
  | "updatedAt"
  | "messages"
  | "rootMessageId"
  | "currentPath"
> & {
  id?: string;
  createdAt?: number;
  updatedAt?: number;
};

/**
 * Helper type for creating new folders
 */
export type NewFolderInput = Omit<
  ChatFolder,
  "id" | "createdAt" | "updatedAt" | "childrenIds"
> & {
  id?: string;
  createdAt?: number;
  updatedAt?: number;
  childrenIds?: string[];
};

/**
 * Storage keys for localStorage
 */
export const STORAGE_KEYS = {
  CHAT_STATE: "chat-state-v2",
  ACTIVE_THREAD: "chat-active-thread",
  UI_PREFERENCES: "chat-ui-preferences",
} as const;

/**
 * Default folder IDs
 */
export const DEFAULT_FOLDERS = {
  GENERAL: "folder-general",
} as const;

/**
 * View mode for messages
 */
export type ViewMode = "linear" | "threaded" | "flat";

/**
 * UI preferences for chat interface
 */
export interface ChatUIPreferences {
  /** Whether sidebar is collapsed */
  sidebarCollapsed: boolean;

  /** Sidebar width in pixels */
  sidebarWidth: number;

  /** Whether to show message timestamps */
  showTimestamps: boolean;

  /** Whether to show branch indicators */
  showBranchIndicators: boolean;

  /** View mode for messages */
  viewMode: ViewMode;

  /** Theme preference */
  theme?: "light" | "dark" | "system";

  /** Font size preference */
  fontSize?: "small" | "medium" | "large";
}
