/**
 * Agent Docs Generator (domain-co-located).
 *
 * Generates AGENTS.md at the repo root from the vibe-coder skill's
 * PROJECT_INSTRUCTIONS (the single source of truth). No file scan.
 *
 * CLAUDE.md is static (`@AGENTS.md`) and not generated - Claude Code
 * resolves the `@` import itself.
 *
 * Tokens replaced: {{AGENT_NAME}} → "Coding Agent";
 *                  {{AGENT_DOCS_FILE}} → "AGENTS.md".
 */

import "server-only";

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { GeneratorDefinition } from "next-vibe/core/generators/shared/shared-inputs";

interface AgentDocTarget {
  fileName: string;
  agentName: string;
}

const TARGETS: AgentDocTarget[] = [
  { fileName: "AGENTS.md", agentName: "Coding Agent" },
];

const HEADER =
  "<!-- AUTO-GENERATED by vibe gen from vibe-coder skill.ts. Do not edit manually. -->\n\n";

export const generator: GeneratorDefinition = {
  key: "agent-docs",
  phase: "default",
  needs: {},
  cacheKey: "agent-docs",
  findInputs() {
    return [
      join(
        process.cwd(),
        "src",
        "vibe",
        "agent",
        "skills",
        "default-skills",
        "vibe-coder",
        "skill.ts",
      ),
    ];
  },
  // Derived from the same fixed TARGETS list the run writes, so the two cannot
  // drift apart when a doc target is added or renamed.
  output: TARGETS.map((target) => target.fileName),
  /** Generate CLAUDE.md + AGENTS.md from PROJECT_INSTRUCTIONS. */
  async generate(ctx) {
    const { PROJECT_INSTRUCTIONS } = await import("./skill");

    const projectRoot = process.cwd();
    let filesWritten = 0;

    for (const target of TARGETS) {
      const content =
        HEADER +
        PROJECT_INSTRUCTIONS.replaceAll(
          "{{AGENT_NAME}}",
          target.agentName,
        ).replaceAll("{{AGENT_DOCS_FILE}}", target.fileName);

      await writeFile(join(projectRoot, target.fileName), content, "utf-8");
      filesWritten++;
      ctx.logger.debug(`Wrote ${target.fileName}`);
    }

    return {
      summary: `agent docs (${filesWritten} files)`,
      counts: { files: filesWritten },
    };
  },
};
