/**
 * Agent Docs Generator (domain-co-located).
 *
 * Generates CLAUDE.md and AGENTS.md at the repo root from the vibe-coder skill's
 * PROJECT_INSTRUCTIONS (the single source of truth). Byte-identical to the former
 * tooling/generators/agent-docs. No file scan.
 *
 * Tokens replaced: {{AGENT_NAME}} → "Claude Code" / "Coding Agent";
 *                  {{AGENT_DOCS_FILE}} → "CLAUDE.md" / "AGENTS.md".
 */

import "server-only";

import { writeFile } from "node:fs/promises";
import { join } from "node:path";

import type {
  GeneratorContext,
  GeneratorResult,
} from "next-vibe/core/generators/shared/shared-inputs";

interface AgentDocTarget {
  fileName: string;
  agentName: string;
}

const TARGETS: AgentDocTarget[] = [
  { fileName: "CLAUDE.md", agentName: "Claude Code" },
  { fileName: "AGENTS.md", agentName: "Coding Agent" },
];

const HEADER =
  "<!-- AUTO-GENERATED by vibe gen from vibe-coder skill.ts. Do not edit manually. -->\n\n";

/** Generate CLAUDE.md + AGENTS.md from PROJECT_INSTRUCTIONS. */
export async function generate(
  ctx: GeneratorContext,
): Promise<GeneratorResult> {
  const { PROJECT_INSTRUCTIONS } =
    await import("next-vibe/agent/skills/default-skills/vibe-coder/skill");

  const projectRoot = process.cwd();
  let filesWritten = 0;

  for (const target of TARGETS) {
    const content =
      HEADER +
      PROJECT_INSTRUCTIONS.replaceAll(
        "{{AGENT_NAME}}",
        target.agentName,
      ).replaceAll("{{AGENT_DOCS_FILE}}", target.fileName);

    await writeFile(join(projectRoot, target.fileName), content, "utf-8");
    filesWritten++;
    ctx.logger.debug(`Wrote ${target.fileName}`);
  }

  return {
    summary: `agent docs (${filesWritten} files)`,
    counts: { files: filesWritten },
  };
}
