/**
 * Chat Database Schema
 * Database tables for chat threads, folders, and messages
 */

import { relations, sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import type { z } from "zod";

import { users } from "@/app/api/[locale]/v1/core/user/db";

import type { DefaultFolderId } from "./config";
import { ChatMessageRoleDB, ThreadStatusDB } from "./enum";
import type { ModelId } from "./model-access/models";
import type { PersonaId } from "./personas/config";
import {
  type CustomPersona,
  customPersonas,
  customPersonasRelations,
  type NewCustomPersona,
} from "./personas/db";

/**
 * Folder metadata structure
 */
interface FolderMetadata {
  customColor?: string;
  customIcon?: string;
  sortPreference?: string;
  viewMode?: string;
}

/**
 * Thread metadata structure
 */
interface ThreadMetadata {
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  frequencyPenalty?: number;
  presencePenalty?: number;
  customSettings?: {
    key: string;
    value: string | number | boolean;
  }[];
}

/**
 * Message metadata structure
 */
interface MessageMetadata {
  generationTime?: number;
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  finishReason?: string;
  streamingTime?: number;
  attachments?: {
    id: string;
    type: string;
    url: string;
  }[];
  voterIds?: string[];
  voteDetails?: Array<{
    userId: string;
    vote: "up" | "down";
    timestamp: number;
  }>;
}

/**
 * Chat Folders Table
 * Hierarchical folder structure for organizing threads
 */
export const chatFolders = pgTable(
  "chat_folders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // Root folder (constant: private, shared, public, incognito)
    rootFolderId: text("root_folder_id").notNull().default("private"),

    // Folder details
    name: text("name").notNull(),
    icon: text("icon"), // lucide icon name or si icon name
    color: text("color"), // hex color for visual distinction

    // Hierarchy - self-reference requires any type to break circular inference
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    parentId: uuid("parent_id").references((): any => chatFolders.id, {
      onDelete: "cascade",
    }),

    // UI state
    expanded: boolean("expanded").default(true).notNull(),
    sortOrder: integer("sort_order").default(0).notNull(),

    // Metadata
    metadata: jsonb("metadata").$type<FolderMetadata>().default({}),

    // Timestamps
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => ({
    // Indexes for common queries
    userIdIdx: index("chat_folders_user_id_idx").on(table.userId),
    rootFolderIdIdx: index("chat_folders_root_folder_id_idx").on(
      table.rootFolderId,
    ),
    parentIdIdx: index("chat_folders_parent_id_idx").on(table.parentId),
    sortOrderIdx: index("chat_folders_sort_order_idx").on(table.sortOrder),
  }),
);

/**
 * Chat Threads Table
 * Represents individual chat conversations
 */
export const chatThreads = pgTable(
  "chat_threads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),

    // Thread details
    title: text("title").notNull(),

    // Root folder (constant: private, shared, public, incognito)
    rootFolderId: text("root_folder_id").$type<DefaultFolderId>().notNull(),

    // Subfolder (UUID reference to chat_folders table, can be null for root-level threads)
    folderId: uuid("folder_id").references(() => chatFolders.id, {
      onDelete: "set null",
    }),

    // Status
    status: text("status", { enum: ThreadStatusDB })
      .notNull()
      .default(ThreadStatusDB[0]),

    // Settings
    defaultModel: text("default_model").$type<ModelId | null>(), // ModelId
    defaultPersona: text("default_tone").$type<PersonaId | null>(), // Persona (DB column is "default_tone" for backwards compatibility)
    systemPrompt: text("system_prompt"),

    // Metadata
    pinned: boolean("pinned").default(false).notNull(),
    archived: boolean("archived").default(false).notNull(),
    tags: jsonb("tags").$type<string[]>().default([]),
    preview: text("preview"), // First user message preview
    metadata: jsonb("metadata").$type<ThreadMetadata>().default({}),

    // Timestamps
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),

    // Full-text search vector (auto-generated by trigger)
    searchVector: text("search_vector"),
  },
  (table) => ({
    // GIN index for full-text search performance
    searchVectorIdx: index("chat_threads_search_vector_idx").using(
      "gin",
      sql`to_tsvector('english', ${table.title} || ' ' || COALESCE(${table.preview}, '') || ' ' || COALESCE(${table.systemPrompt}, ''))`,
    ),
    // Additional indexes for common queries
    userIdIdx: index("chat_threads_user_id_idx").on(table.userId),
    rootFolderIdIdx: index("chat_threads_root_folder_id_idx").on(
      table.rootFolderId,
    ),
    folderIdIdx: index("chat_threads_folder_id_idx").on(table.folderId),
    statusIdx: index("chat_threads_status_idx").on(table.status),
    createdAtIdx: index("chat_threads_created_at_idx").on(table.createdAt),
    updatedAtIdx: index("chat_threads_updated_at_idx").on(table.updatedAt),
  }),
);

/**
 * Chat Messages Table
 * Individual messages within threads, supporting branching/threading
 */
export const chatMessages = pgTable(
  "chat_messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    threadId: uuid("thread_id")
      .notNull()
      .references(() => chatThreads.id, { onDelete: "cascade" }),

    // Message content
    role: text("role", { enum: ChatMessageRoleDB }).notNull(),
    content: text("content").notNull(),

    // Threading/branching - self-reference requires any type to break circular inference
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    parentId: uuid("parent_id").references((): any => chatMessages.id, {
      onDelete: "cascade",
    }),
    depth: integer("depth").default(0).notNull(),

    // Author information (for multi-user support)
    authorId: text("author_id"), // User ID or "local"
    authorName: text("author_name"),
    authorAvatar: text("author_avatar"),
    authorColor: text("author_color"),
    isAI: boolean("is_ai").default(false).notNull(),

    // AI-specific fields
    model: text("model"), // ModelId if AI message
    persona: text("tone"), // Persona used (DB column is "tone" for backwards compatibility)

    // Error information (for error messages)
    errorType: text("error_type"),
    errorMessage: text("error_message"),
    errorCode: text("error_code"),

    // Metadata
    edited: boolean("edited").default(false).notNull(),
    originalId: uuid("original_id"), // If this is an edit
    tokens: integer("tokens"),
    collapsed: boolean("collapsed").default(false).notNull(),
    metadata: jsonb("metadata").$type<MessageMetadata>().default({}),

    // Voting
    upvotes: integer("upvotes").default(0).notNull(),
    downvotes: integer("downvotes").default(0).notNull(),

    // Timestamps
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),

    // Full-text search vector (auto-generated by trigger)
    searchVector: text("search_vector"),
  },
  (table) => ({
    // GIN index for full-text search performance
    searchVectorIdx: index("chat_messages_search_vector_idx").using(
      "gin",
      sql`to_tsvector('english', ${table.content})`,
    ),
    // Additional indexes for common queries
    threadIdIdx: index("chat_messages_thread_id_idx").on(table.threadId),
    parentIdIdx: index("chat_messages_parent_id_idx").on(table.parentId),
    roleIdx: index("chat_messages_role_idx").on(table.role),
    createdAtIdx: index("chat_messages_created_at_idx").on(table.createdAt),
  }),
);

/**
 * Relations
 */
export const chatFoldersRelations = relations(chatFolders, ({ one, many }) => ({
  user: one(users, {
    fields: [chatFolders.userId],
    references: [users.id],
  }),
  parent: one(chatFolders, {
    fields: [chatFolders.parentId],
    references: [chatFolders.id],
    relationName: "folderHierarchy",
  }),
  children: many(chatFolders, {
    relationName: "folderHierarchy",
  }),
  threads: many(chatThreads),
}));

export const chatThreadsRelations = relations(chatThreads, ({ one, many }) => ({
  user: one(users, {
    fields: [chatThreads.userId],
    references: [users.id],
  }),
  folder: one(chatFolders, {
    fields: [chatThreads.folderId],
    references: [chatFolders.id],
  }),
  messages: many(chatMessages),
}));

export const chatMessagesRelations = relations(
  chatMessages,
  ({ one, many }) => ({
    thread: one(chatThreads, {
      fields: [chatMessages.threadId],
      references: [chatThreads.id],
    }),
    parent: one(chatMessages, {
      fields: [chatMessages.parentId],
      references: [chatMessages.id],
      relationName: "messageTree",
    }),
    children: many(chatMessages, {
      relationName: "messageTree",
    }),
  }),
);

/**
 * Schemas for validation
 */
export const selectChatFolderSchema = createSelectSchema(chatFolders);
export const insertChatFolderSchema = createInsertSchema(chatFolders);

export const selectChatThreadSchema = createSelectSchema(chatThreads);
export const insertChatThreadSchema = createInsertSchema(chatThreads);

export const selectChatMessageSchema = createSelectSchema(chatMessages);
export const insertChatMessageSchema = createInsertSchema(chatMessages);

/**
 * Types
 */
export type ChatFolder = z.infer<typeof selectChatFolderSchema>;
export type NewChatFolder = z.infer<typeof insertChatFolderSchema>;

export type ChatThread = z.infer<typeof selectChatThreadSchema>;
export type NewChatThread = z.infer<typeof insertChatThreadSchema>;

export type ChatMessage = z.infer<typeof selectChatMessageSchema>;
export type NewChatMessage = z.infer<typeof insertChatMessageSchema>;

/**
 * Re-export custom personas table, relations and types
 * Note: Relations are also defined in personas/db.ts but re-exported here
 * for Drizzle's query API to work properly
 */
export { customPersonas };
export { customPersonasRelations };
export type { CustomPersona, NewCustomPersona };
