/**
 * Vision Model Enums and Lookups
 *
 * Three separate vision model categories for bridging non-native modalities to text:
 * - ImageVisionModelId: models that can analyze images
 * - VideoVisionModelId: models that can analyze video
 * - AudioVisionModelId: models that can analyze audio/music
 *
 * Each is a subset of ChatModelId — values are shared string IDs,
 * lookups go into the same chatModelOptionsIndex via getChatModelById.
 *
 * Enums are AUTO-GENERATED from chatModelDefinitions inputs field.
 * Re-run: vibe update-all-model-prices or vibe gen
 */

import type { AnyModelId } from "@/app/api/[locale]/agent/models/models";

import type { ChatModelOption } from "./models";
import { chatModelOptions, chatModelOptionsIndex, ChatModelId } from "./models";

// Auto-generated enums — do not define inline, regenerated by price updater
import {
  ImageVisionModelId,
  VideoVisionModelId,
  AudioVisionModelId,
} from "./vision-models.generated";

export { ImageVisionModelId, VideoVisionModelId, AudioVisionModelId };

// ============================================
// OPTIONS + LOOKUPS
// ============================================

// Filter chatModelOptions using the model's inputs field — single source of truth
export const imageVisionModelOptions: ChatModelOption[] =
  chatModelOptions.filter((m) => m.inputs.includes("image"));

export const videoVisionModelOptions: ChatModelOption[] =
  chatModelOptions.filter((m) => m.inputs.includes("video"));

export const audioVisionModelOptions: ChatModelOption[] =
  chatModelOptions.filter((m) => m.inputs.includes("audio"));

// O(1) membership check sets — uses string for cross-enum compatibility
// (vision model IDs are a subset of ChatModelId strings, but callers may pass AnyModelId)
const imageVisionIdSet: ReadonlySet<string> = new Set(
  imageVisionModelOptions.map((m) => m.id),
);
const videoVisionIdSet: ReadonlySet<string> = new Set(
  videoVisionModelOptions.map((m) => m.id),
);
const audioVisionIdSet: ReadonlySet<string> = new Set(
  audioVisionModelOptions.map((m) => m.id),
);

/** Check if a model ID belongs to the image vision pool */
export function isImageVisionModel(id: AnyModelId): boolean {
  return imageVisionIdSet.has(id);
}
/** Check if a model ID belongs to the video vision pool */
export function isVideoVisionModel(id: AnyModelId): boolean {
  return videoVisionIdSet.has(id);
}
/** Check if a model ID belongs to the audio vision pool */
export function isAudioVisionModel(id: AnyModelId): boolean {
  return audioVisionIdSet.has(id);
}

// Dropdown option lists for selector widgets
export const ImageVisionModelIdOptions = Object.values(ImageVisionModelId).map(
  (id) => ({
    value: id,
    label: chatModelOptionsIndex[id]?.name ?? id,
  }),
);

export const VideoVisionModelIdOptions = Object.values(VideoVisionModelId).map(
  (id) => ({
    value: id,
    label: chatModelOptionsIndex[id]?.name ?? id,
  }),
);

export const AudioVisionModelIdOptions = Object.values(AudioVisionModelId).map(
  (id) => ({
    value: id,
    label: chatModelOptionsIndex[id]?.name ?? id,
  }),
);

const fallback = chatModelOptionsIndex[ChatModelId.KIMI_K2]!;

export function getImageVisionModelById(
  modelId: ImageVisionModelId,
): ChatModelOption {
  return chatModelOptionsIndex[modelId] ?? fallback;
}

export function getVideoVisionModelById(
  modelId: VideoVisionModelId,
): ChatModelOption {
  return chatModelOptionsIndex[modelId] ?? fallback;
}

export function getAudioVisionModelById(
  modelId: AudioVisionModelId,
): ChatModelOption {
  return chatModelOptionsIndex[modelId] ?? fallback;
}
