/**
 * Vision Model Lookups
 *
 * Three separate vision model categories for bridging non-native modalities to text:
 * - ImageVisionModelId: models that can analyze images
 * - VideoVisionModelId: models that can analyze video
 * - AudioVisionModelId: models that can analyze audio/music
 *
 * Each is a TypeScript enum auto-generated from chatModelDefinitions inputs field.
 * Options are built by importing the enum members directly - no runtime iteration.
 *
 * Re-run: vibe update-all-model-prices or vibe gen
 */

import { z } from "zod";

import type { ModelOptionTokenBased } from "@/app/api/[locale]/agent/models/models";
import type { JwtPayloadType } from "@/app/api/[locale]/user/auth/types";
import { ModelSelectionType } from "../chat/skills/enum";
import {
  filterRoleModels,
  isModelOptionTokenBased,
  type ModelProviderEnvAvailability,
} from "../models/models";
import {
  filtersSelectionSchema,
  sharedFilterPropsSchema,
} from "../models/selection";

import { chatModelOptionsIndex } from "./models";

// Auto-generated enums - do not edit, regenerated by price updater
import {
  AudioVisionModelId,
  ImageVisionModelId,
  VideoVisionModelId,
} from "./vision-models.generated";

export { AudioVisionModelId, ImageVisionModelId, VideoVisionModelId };

// ============================================
// TYPED OPTION TYPES - one per vision modality
// ============================================

/** Token-based model that accepts image input. */
export type ImageVisionModelOption = ModelOptionTokenBased & {
  id: ImageVisionModelId;
};

/** Token-based model that accepts video input. */
export type VideoVisionModelOption = ModelOptionTokenBased & {
  id: VideoVisionModelId;
};

/** Token-based model that accepts audio input. */
export type AudioVisionModelOption = ModelOptionTokenBased & {
  id: AudioVisionModelId;
};

// ============================================
// OPTIONS INDEXES
// Built by directly looking up each enum value in chatModelOptionsIndex.
// ImageVisionModelId / VideoVisionModelId / AudioVisionModelId values are a strict
// subset of ChatModelId string values, so chatModelOptionsIndex[id] always resolves.
// ============================================

function makeImageVisionOption(
  id: ImageVisionModelId,
): ImageVisionModelOption | undefined {
  const opt = chatModelOptionsIndex[id];
  if (!opt || !isModelOptionTokenBased(opt)) {
    return undefined;
  }
  return { ...opt, id };
}

function makeVideoVisionOption(
  id: VideoVisionModelId,
): VideoVisionModelOption | undefined {
  const opt = chatModelOptionsIndex[id];
  if (!opt || !isModelOptionTokenBased(opt)) {
    return undefined;
  }
  return { ...opt, id };
}

function makeAudioVisionOption(
  id: AudioVisionModelId,
): AudioVisionModelOption | undefined {
  const opt = chatModelOptionsIndex[id];
  if (!opt || !isModelOptionTokenBased(opt)) {
    return undefined;
  }
  return { ...opt, id };
}

const imageVisionModelOptionsIndex: Record<
  ImageVisionModelId,
  ImageVisionModelOption | undefined
> = {
  [ImageVisionModelId.GPT_5_4]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_4,
  ),
  [ImageVisionModelId.GPT_5_4_PRO]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_4_PRO,
  ),
  [ImageVisionModelId.GPT_5_4_MINI]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_4_MINI,
  ),
  [ImageVisionModelId.GPT_5_4_NANO]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_4_NANO,
  ),
  [ImageVisionModelId.GPT_5_3_CODEX]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_3_CODEX,
  ),
  [ImageVisionModelId.GPT_5_3_CHAT]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_3_CHAT,
  ),
  [ImageVisionModelId.GPT_5_2]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_2,
  ),
  [ImageVisionModelId.GPT_5_2_CHAT]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_2_CHAT,
  ),
  [ImageVisionModelId.GPT_5_2_PRO]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_2_PRO,
  ),
  [ImageVisionModelId.GPT_5_1]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_1,
  ),
  [ImageVisionModelId.GPT_5_1_CODEX]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_1_CODEX,
  ),
  [ImageVisionModelId.GTP_5_PRO]: makeImageVisionOption(
    ImageVisionModelId.GTP_5_PRO,
  ),
  [ImageVisionModelId.GPT_5_CODEX]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_CODEX,
  ),
  [ImageVisionModelId.GPT_5]: makeImageVisionOption(ImageVisionModelId.GPT_5),
  [ImageVisionModelId.GPT_5_MINI]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_MINI,
  ),
  [ImageVisionModelId.GPT_5_NANO]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_NANO,
  ),
  [ImageVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS]:
    makeImageVisionOption(
      ImageVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS,
    ),
  [ImageVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW,
  ),
  [ImageVisionModelId.GEMINI_3_FLASH]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_3_FLASH,
  ),
  [ImageVisionModelId.GEMINI_2_5_PRO]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_2_5_PRO,
  ),
  [ImageVisionModelId.GEMINI_2_5_FLASH]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_2_5_FLASH,
  ),
  [ImageVisionModelId.GEMINI_2_5_FLASH_LITE]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_2_5_FLASH_LITE,
  ),
  [ImageVisionModelId.KIMI_K2_5]: makeImageVisionOption(
    ImageVisionModelId.KIMI_K2_5,
  ),
  [ImageVisionModelId.GROK_4_FAST]: makeImageVisionOption(
    ImageVisionModelId.GROK_4_FAST,
  ),
  [ImageVisionModelId.GROK_4]: makeImageVisionOption(ImageVisionModelId.GROK_4),
  [ImageVisionModelId.GROK_4_20]: makeImageVisionOption(
    ImageVisionModelId.GROK_4_20,
  ),
  [ImageVisionModelId.CLAUDE_HAIKU_4_5]: makeImageVisionOption(
    ImageVisionModelId.CLAUDE_HAIKU_4_5,
  ),
  [ImageVisionModelId.CLAUDE_SONNET_4_5]: makeImageVisionOption(
    ImageVisionModelId.CLAUDE_SONNET_4_5,
  ),
  [ImageVisionModelId.CLAUDE_SONNET_4_6]: makeImageVisionOption(
    ImageVisionModelId.CLAUDE_SONNET_4_6,
  ),
  [ImageVisionModelId.CLAUDE_OPUS_4_5]: makeImageVisionOption(
    ImageVisionModelId.CLAUDE_OPUS_4_5,
  ),
  [ImageVisionModelId.CLAUDE_OPUS_4_6]: makeImageVisionOption(
    ImageVisionModelId.CLAUDE_OPUS_4_6,
  ),
  [ImageVisionModelId.GLM_4_5V]: makeImageVisionOption(
    ImageVisionModelId.GLM_4_5V,
  ),
  [ImageVisionModelId.GEMINI_3_1_FLASH_IMAGE_PREVIEW]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_3_1_FLASH_IMAGE_PREVIEW,
  ),
  [ImageVisionModelId.GEMINI_3_PRO_IMAGE_PREVIEW]: makeImageVisionOption(
    ImageVisionModelId.GEMINI_3_PRO_IMAGE_PREVIEW,
  ),
  [ImageVisionModelId.GPT_5_IMAGE_MINI]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_IMAGE_MINI,
  ),
  [ImageVisionModelId.GPT_5_IMAGE]: makeImageVisionOption(
    ImageVisionModelId.GPT_5_IMAGE,
  ),
};

const videoVisionModelOptionsIndex: Record<
  VideoVisionModelId,
  VideoVisionModelOption | undefined
> = {
  [VideoVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS]:
    makeVideoVisionOption(
      VideoVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS,
    ),
  [VideoVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW]: makeVideoVisionOption(
    VideoVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW,
  ),
  [VideoVisionModelId.GEMINI_3_FLASH]: makeVideoVisionOption(
    VideoVisionModelId.GEMINI_3_FLASH,
  ),
  [VideoVisionModelId.GEMINI_2_5_PRO]: makeVideoVisionOption(
    VideoVisionModelId.GEMINI_2_5_PRO,
  ),
  [VideoVisionModelId.GEMINI_2_5_FLASH]: makeVideoVisionOption(
    VideoVisionModelId.GEMINI_2_5_FLASH,
  ),
  [VideoVisionModelId.GEMINI_2_5_FLASH_LITE]: makeVideoVisionOption(
    VideoVisionModelId.GEMINI_2_5_FLASH_LITE,
  ),
};

const audioVisionModelOptionsIndex: Record<
  AudioVisionModelId,
  AudioVisionModelOption | undefined
> = {
  [AudioVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS]:
    makeAudioVisionOption(
      AudioVisionModelId.GEMINI_3_1_PRO_PREVIEW_CUSTOM_TOOLS,
    ),
  [AudioVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW]: makeAudioVisionOption(
    AudioVisionModelId.GEMINI_3_1_FLASH_LITE_PREVIEW,
  ),
  [AudioVisionModelId.GEMINI_3_FLASH]: makeAudioVisionOption(
    AudioVisionModelId.GEMINI_3_FLASH,
  ),
  [AudioVisionModelId.GEMINI_2_5_PRO]: makeAudioVisionOption(
    AudioVisionModelId.GEMINI_2_5_PRO,
  ),
  [AudioVisionModelId.GEMINI_2_5_FLASH]: makeAudioVisionOption(
    AudioVisionModelId.GEMINI_2_5_FLASH,
  ),
  [AudioVisionModelId.GEMINI_2_5_FLASH_LITE]: makeAudioVisionOption(
    AudioVisionModelId.GEMINI_2_5_FLASH_LITE,
  ),
};

export const imageVisionModelOptions: ImageVisionModelOption[] = Object.values(
  imageVisionModelOptionsIndex,
).filter((m): m is ImageVisionModelOption => m !== undefined);

export const videoVisionModelOptions: VideoVisionModelOption[] = Object.values(
  videoVisionModelOptionsIndex,
).filter((m): m is VideoVisionModelOption => m !== undefined);

export const audioVisionModelOptions: AudioVisionModelOption[] = Object.values(
  audioVisionModelOptionsIndex,
).filter((m): m is AudioVisionModelOption => m !== undefined);

// ============================================
// DROPDOWN OPTIONS
// ============================================

export const ImageVisionModelIdOptions = imageVisionModelOptions.map((m) => ({
  value: m.id,
  label: m.name,
}));

export const VideoVisionModelIdOptions = videoVisionModelOptions.map((m) => ({
  value: m.id,
  label: m.name,
}));

export const AudioVisionModelIdOptions = audioVisionModelOptions.map((m) => ({
  value: m.id,
  label: m.name,
}));

// ============================================
// GETTERS
// ============================================

export function getImageVisionModelById(
  modelId: ImageVisionModelId,
): ImageVisionModelOption | undefined {
  return imageVisionModelOptionsIndex[modelId];
}

export function getVideoVisionModelById(
  modelId: VideoVisionModelId,
): VideoVisionModelOption | undefined {
  return videoVisionModelOptionsIndex[modelId];
}

export function getAudioVisionModelById(
  modelId: AudioVisionModelId,
): AudioVisionModelOption | undefined {
  return audioVisionModelOptionsIndex[modelId];
}

// ============================================================
// VISION MODEL SELECTION SCHEMAS
// ============================================================

export const imageVisionModelSelectionSchema = z.discriminatedUnion(
  "selectionType",
  [
    z
      .object({
        selectionType: z.literal(ModelSelectionType.MANUAL),
        manualModelId: z.enum(ImageVisionModelId),
      })
      .merge(sharedFilterPropsSchema),
    filtersSelectionSchema,
  ],
);
export type ImageVisionModelSelection = z.infer<
  typeof imageVisionModelSelectionSchema
>;

export const videoVisionModelSelectionSchema = z.discriminatedUnion(
  "selectionType",
  [
    z
      .object({
        selectionType: z.literal(ModelSelectionType.MANUAL),
        manualModelId: z.enum(VideoVisionModelId),
      })
      .merge(sharedFilterPropsSchema),
    filtersSelectionSchema,
  ],
);
export type VideoVisionModelSelection = z.infer<
  typeof videoVisionModelSelectionSchema
>;

export const audioVisionModelSelectionSchema = z.discriminatedUnion(
  "selectionType",
  [
    z
      .object({
        selectionType: z.literal(ModelSelectionType.MANUAL),
        manualModelId: z.enum(AudioVisionModelId),
      })
      .merge(sharedFilterPropsSchema),
    filtersSelectionSchema,
  ],
);
export type AudioVisionModelSelection = z.infer<
  typeof audioVisionModelSelectionSchema
>;

// ============================================================
// VISION MODEL RESOLUTION
// ============================================================

export function filterImageVisionModels(
  selection: ImageVisionModelSelection | null | undefined,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): ImageVisionModelOption[] {
  return filterRoleModels(imageVisionModelOptions, selection, user, env);
}

export function getBestImageVisionModel(
  selection: ImageVisionModelSelection,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): ImageVisionModelOption | null {
  return filterImageVisionModels(selection, user, env)[0] ?? null;
}

export function filterVideoVisionModels(
  selection: VideoVisionModelSelection | null | undefined,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): VideoVisionModelOption[] {
  return filterRoleModels(videoVisionModelOptions, selection, user, env);
}

export function getBestVideoVisionModel(
  selection: VideoVisionModelSelection,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): VideoVisionModelOption | null {
  return filterVideoVisionModels(selection, user, env)[0] ?? null;
}

export function filterAudioVisionModels(
  selection: AudioVisionModelSelection | null | undefined,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): AudioVisionModelOption[] {
  return filterRoleModels(audioVisionModelOptions, selection, user, env);
}

export function getBestAudioVisionModel(
  selection: AudioVisionModelSelection,
  user: JwtPayloadType,
  env: ModelProviderEnvAvailability,
): AudioVisionModelOption | null {
  return filterAudioVisionModels(selection, user, env)[0] ?? null;
}
