/**
 * Skill Embedding Type
 *
 * Embedding data lives in skill.embedding.ts sibling files, generated by `vibe gen`.
 * Decoupled from skill.ts so large embedding arrays don't bloat the skill definition.
 */

export interface SkillEmbedding {
  /** Skill ID — must match the skill's id field */
  skillId: string;
  /** SHA-256 of (cortex path + systemPrompt). Written by `vibe gen`. */
  embeddingHash: string;
  /** Pre-computed 3072-dim embedding. Written by `vibe gen`. */
  // prettier-ignore
  embedding: number[];
}
