"use custom";
/**
 * Expo Router compatibility wrapper for Next.js layout.tsx
 *
 * This file is auto-generated by the generate-expo-indexes endpoint
 * Do not edit manually unless you add a "use custom" directive at the top.
 *
 * This wrapper handles:
 * - Dynamic import with server-only error handling
 * - Async component loading (Next.js layouts can be async Server Components)
 * - URL params conversion (Next.js uses async params, Expo Router uses hooks)
 * - Only renders Slot (layouts must only contain Screen children)
 * - Error handling with graceful fallbacks
 * - Type-safe params forwarding
 */

import RootLayoutNative from "@/app/[locale]/layout";

export default RootLayoutNative;
