/**
 * Expo Router compatibility wrapper for Next.js page.tsx
 *
 * This file is auto-generated by scripts/generate-expo-indexes.ts
 * Do not edit manually unless you add a "use-custom" directive at the top.
 *
 * This wrapper handles:
 * - Async component loading (Next.js pages can be async Server Components)
 * - URL params conversion (Next.js uses async params, Expo Router uses hooks)
 * - Loading states with ActivityIndicator
 * - Error handling
 * - Type-safe params forwarding
 */

import PageComponent from "@/app/[locale]/help/page";
import { createPageWrapper } from "@/app/api/[locale]/v1/core/system/unified-ui/react-native/platform-helpers";

/**
 * Wrapper component that converts Expo Router's synchronous params
 * to Next.js 15's async params format
 */
export default createPageWrapper(PageComponent);
