/**
 * AUTO-GENERATED FILE - DO NOT EDIT - CLIENT-SAFE
 * Generated by generators/email-templates
 *
 * Templates found: 8
 * Client-safe: No server-only imports
 */

"use client";

import type { TemplateCachedMetadata } from "./types";

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 */
export const templateMetadataMap: Record<string, TemplateCachedMetadata> = {
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "app.api.emails.templates.contact.form.meta.name",
    description: "app.api.emails.templates.contact.form.meta.description",
    category: "contact",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "Anfrage zu Ihren Dienstleistungen",
      message: "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.unsubscribe.meta.name",
    description: "app.api.emails.templates.newsletter.unsubscribe.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.welcome.meta.name",
    description: "app.api.emails.templates.newsletter.welcome.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.confirm.meta.name",
    description: "app.api.emails.templates.password.reset.confirm.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.request.meta.name",
    description: "app.api.emails.templates.password.reset.request.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
    },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "app.admin.emails.templates.templates.signup.welcome.meta.name",
    description: "app.admin.emails.templates.templates.signup.welcome.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "app.api.emails.templates.subscription.success.meta.name",
    description: "app.api.emails.templates.subscription.success.meta.description",
    category: "subscription",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      firstName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
    },
  },
  "user-welcome": {
    id: "user-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.users.welcome.meta.name",
    description: "app.api.emails.templates.users.welcome.meta.description",
    category: "users",
    path: "/src/app/api/[locale]/users/create/email.tsx",
    exampleProps: {
      userId: "example-user-id-123",
      email: "max@example.com",
      privateName: "Max",
      publicName: "Max Mustermann",
      leadId: "example-lead-id-456",
    },
  },
};

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(id: string): TemplateCachedMetadata | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(category: string): TemplateCachedMetadata[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}
