/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/email-templates
 *
 * Templates found: 7
 */

import type emailTemplate0 from "@/app/api/[locale]/contact/email";
import type emailTemplate1 from "@/app/api/[locale]/newsletter/subscribe/email";
import type emailTemplate2 from "@/app/api/[locale]/newsletter/unsubscribe/email";
import type emailTemplate3 from "@/app/api/[locale]/subscription/email";
import type emailTemplate4 from "@/app/api/[locale]/user/public/reset-password/confirm/email";
import type emailTemplate5 from "@/app/api/[locale]/user/public/reset-password/request/email";
import type emailTemplate6 from "@/app/api/[locale]/user/public/signup/email";
import type { CountryLanguage } from "@/i18n/core/config";

import type {
  AnyTemplateConstraint,
  TemplateCachedMetadata,
  TranslatedPreviewFieldConfig,
} from "./types";

/**
 * Union type of all email template definitions
 * Each template has its own specific props type
 */
type AnyEmailTemplate =
  | typeof emailTemplate0
  | typeof emailTemplate1
  | typeof emailTemplate2
  | typeof emailTemplate3
  | typeof emailTemplate4
  | typeof emailTemplate5
  | typeof emailTemplate6;

/**
 * Lazy-loaded template registry with dynamic imports
 */
const templateLoaders: Record<string, () => Promise<AnyEmailTemplate>> = {
  "contact-form": async () =>
    (await import("@/app/api/[locale]/contact/email")).default,
  "newsletter-unsubscribe": async () =>
    (await import("@/app/api/[locale]/newsletter/unsubscribe/email")).default,
  "newsletter-welcome": async () =>
    (await import("@/app/api/[locale]/newsletter/subscribe/email")).default,
  "password-reset-confirm": async () =>
    (
      await import("@/app/api/[locale]/user/public/reset-password/confirm/email")
    ).default,
  "password-reset-request": async () =>
    (
      await import("@/app/api/[locale]/user/public/reset-password/request/email")
    ).default,
  "signup-welcome": async () =>
    (await import("@/app/api/[locale]/user/public/signup/email")).default,
  "subscription-success": async () =>
    (await import("@/app/api/[locale]/subscription/email")).default,
};

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 * Actual components are lazy-loaded
 */
export const templateMetadataMap: Record<
  string,
  TemplateCachedMetadata<string>
> = {
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "emailTemplates.contactForm.meta.name",
    description: "emailTemplates.contactForm.meta.description",
    category: "emailTemplates.contactForm.meta.category",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "Anfrage zu Ihren Dienstleistungen",
      message:
        "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "emailTemplates.unsubscribe.name",
    description: "emailTemplates.unsubscribe.description",
    category: "emailTemplates.unsubscribe.category",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "emailTemplates.confirm.name",
    description: "emailTemplates.confirm.description",
    category: "emailTemplates.confirm.category",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "emailTemplates.request.name",
    description: "emailTemplates.request.description",
    category: "emailTemplates.request.category",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
    },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "emailTemplates.welcome.name",
    description: "emailTemplates.welcome.description",
    category: "emailTemplates.welcome.category",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "emailTemplates.success.name",
    description: "emailTemplates.success.description",
    category: "emailTemplates.success.category",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
    },
  },
};

/**
 * Get template by ID (lazy loads on first access)
 * Returns the template with its specific props type
 */
export async function getTemplate(
  id: string,
): Promise<AnyEmailTemplate | undefined> {
  const loader = templateLoaders[id];
  if (!loader) {
    return undefined;
  }

  return await loader();
}

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata<string> | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template IDs
 */
export function getAllTemplateIds(): string[] {
  return Object.keys(templateLoaders);
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata<string>[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata<string>[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}

/**
 * Check if template exists
 */
export function hasTemplate(id: string): boolean {
  return id in templateLoaders;
}

/**
 * Translated metadata shape (all keys resolved to plain strings)
 */
export interface TranslatedTemplateMetadata {
  id: string;
  version: string;
  name: string;
  description: string;
  category: string;
  path: string;
}

/**
 * Get template metadata with name/description/category translated via the
 * template's own scopedTranslation.
 */
export async function getTranslatedTemplateMetadata(
  id: string,
  locale: CountryLanguage,
): Promise<TranslatedTemplateMetadata | undefined> {
  const template = await getTemplate(id);
  if (!template) {
    return undefined;
  }
  const t = (template as AnyTemplateConstraint).scopedTranslation.scopedT(
    locale,
  ).t;
  const meta = templateMetadataMap[id];
  if (!meta) {
    return undefined;
  }
  return {
    id: meta.id,
    version: meta.version,
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch: meta keys and t are from the same template instance
    name: t(meta.name as never) as string,
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch
    description: t(meta.description as never) as string,
    // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch
    category: t(meta.category as never) as string,
    path: meta.path,
  };
}

/**
 * Get all templates with translated metadata.
 */
export async function getAllTranslatedTemplateMetadata(
  locale: CountryLanguage,
): Promise<TranslatedTemplateMetadata[]> {
  const ids = getAllTemplateIds();
  const results = await Promise.all(
    ids.map((id) => getTranslatedTemplateMetadata(id, locale)),
  );
  return results.filter(
    (m): m is TranslatedTemplateMetadata => m !== undefined,
  );
}

/**
 * Translate all previewFields labels/descriptions in a loaded template.
 */
export function translatePreviewFields(
  template: AnyTemplateConstraint,
  locale: CountryLanguage,
): Record<string, TranslatedPreviewFieldConfig> {
  const t = template.scopedTranslation.scopedT(locale).t;
  const previewFields = (
    template as {
      meta: {
        previewFields?: Record<
          string,
          {
            type: string;
            label: string;
            description?: string;
            defaultValue?: string | number | boolean;
            required?: boolean;
            options?: { value: string; label: string }[];
            min?: number;
            max?: number;
            rows?: number;
          }
        >;
      };
    }
  ).meta.previewFields;
  if (!previewFields) {
    return {};
  }
  const result: Record<string, TranslatedPreviewFieldConfig> = {};
  for (const [key, field] of Object.entries(previewFields)) {
    result[key] = {
      type: field.type as TranslatedPreviewFieldConfig["type"],
      // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch
      label: t(field.label as never) as string,
      description: field.description
        ? // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch
          (t(field.description as never) as string)
        : undefined,
      defaultValue: field.defaultValue,
      required: field.required,
      options: field.options?.map((o) => ({
        value: o.value,
        // eslint-disable-next-line oxlint-plugin-restricted/restricted-syntax -- sealed dispatch
        label: t(o.label as never) as string,
      })),
      min: field.min,
      max: field.max,
      rows: field.rows,
    };
  }
  return result;
}
