/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/email-templates
 *
 * Templates found: 10
 */

import type { TemplateCachedMetadata } from "./types";

import type emailTemplate0 from "@/app/api/[locale]/leads/batch/email";
import type emailTemplate1 from "@/app/api/[locale]/contact/email";
import type emailTemplate2 from "@/app/api/[locale]/leads/create/email";
import type emailTemplate3 from "@/app/api/[locale]/newsletter/unsubscribe/email";
import type emailTemplate4 from "@/app/api/[locale]/newsletter/subscribe/email";
import type emailTemplate5 from "@/app/api/[locale]/user/public/reset-password/confirm/email";
import type emailTemplate6 from "@/app/api/[locale]/user/public/reset-password/request/email";
import type emailTemplate7 from "@/app/api/[locale]/user/public/signup/email";
import type emailTemplate8 from "@/app/api/[locale]/subscription/email";
import type emailTemplate9 from "@/app/api/[locale]/users/create/email";

/**
 * Union type of all email template definitions
 * Each template has its own specific props type
 */
type AnyEmailTemplate =
  | typeof emailTemplate0
  | typeof emailTemplate1
  | typeof emailTemplate2
  | typeof emailTemplate3
  | typeof emailTemplate4
  | typeof emailTemplate5
  | typeof emailTemplate6
  | typeof emailTemplate7
  | typeof emailTemplate8
  | typeof emailTemplate9;

/**
 * Lazy-loaded template registry with dynamic imports
 * Templates are loaded on-demand for optimal bundle size
 */
const templateLoaders: Record<string, () => Promise<AnyEmailTemplate>> = {
  "batch-update": async () =>
    (await import("@/app/api/[locale]/leads/batch/email")).default,
  "contact-form": async () =>
    (await import("@/app/api/[locale]/contact/email")).default,
  "lead-welcome": async () =>
    (await import("@/app/api/[locale]/leads/create/email")).default,
  "newsletter-unsubscribe": async () =>
    (await import("@/app/api/[locale]/newsletter/unsubscribe/email")).default,
  "newsletter-welcome": async () =>
    (await import("@/app/api/[locale]/newsletter/subscribe/email")).default,
  "password-reset-confirm": async () =>
    (
      await import(
        "@/app/api/[locale]/user/public/reset-password/confirm/email"
      )
    ).default,
  "password-reset-request": async () =>
    (
      await import(
        "@/app/api/[locale]/user/public/reset-password/request/email"
      )
    ).default,
  "signup-welcome": async () =>
    (await import("@/app/api/[locale]/user/public/signup/email")).default,
  "subscription-success": async () =>
    (await import("@/app/api/[locale]/subscription/email")).default,
  "user-welcome": async () =>
    (await import("@/app/api/[locale]/users/create/email")).default,
};

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 * Actual components are lazy-loaded
 */
export const templateMetadataMap: Record<string, TemplateCachedMetadata> = {
  "batch-update": {
    id: "batch-update",
    version: "1.0.0",
    name: "app.api.emails.templates.leads.batch.update.meta.name",
    description: "app.api.emails.templates.leads.batch.update.meta.description",
    category: "leads",
    path: "/src/app/api/[locale]/leads/batch/email.tsx",
  },
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "app.api.emails.templates.contact.form.meta.name",
    description: "app.api.emails.templates.contact.form.meta.description",
    category: "contact",
    path: "/src/app/api/[locale]/contact/email.tsx",
  },
  "lead-welcome": {
    id: "lead-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.leads.welcome.meta.name",
    description: "app.api.emails.templates.leads.welcome.meta.description",
    category: "leads",
    path: "/src/app/api/[locale]/leads/create/email.tsx",
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.unsubscribe.meta.name",
    description:
      "app.api.emails.templates.newsletter.unsubscribe.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.welcome.meta.name",
    description: "app.api.emails.templates.newsletter.welcome.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.confirm.meta.name",
    description:
      "app.api.emails.templates.password.reset.confirm.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.request.meta.name",
    description:
      "app.api.emails.templates.password.reset.request.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.signup.welcome.meta.name",
    description: "app.api.emails.templates.signup.welcome.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "app.api.emails.templates.subscription.success.meta.name",
    description:
      "app.api.emails.templates.subscription.success.meta.description",
    category: "subscription",
    path: "/src/app/api/[locale]/subscription/email.tsx",
  },
  "user-welcome": {
    id: "user-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.users.welcome.meta.name",
    description: "app.api.emails.templates.users.welcome.meta.description",
    category: "users",
    path: "/src/app/api/[locale]/users/create/email.tsx",
  },
};

/**
 * Get template by ID (lazy loads on first access)
 * Returns the template with its specific props type
 */
export async function getTemplate(
  id: string,
): Promise<AnyEmailTemplate | undefined> {
  const loader = templateLoaders[id];
  if (!loader) {
    return undefined;
  }

  return await loader();
}

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template IDs
 */
export function getAllTemplateIds(): string[] {
  return Object.keys(templateLoaders);
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}

/**
 * Check if template exists
 */
export function hasTemplate(id: string): boolean {
  return id in templateLoaders;
}
