/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/email-templates
 *
 * Templates found: 8
 */

import type { TemplateCachedMetadata } from "./types";

import type emailTemplate0 from "@/app/api/[locale]/contact/email";
import type emailTemplate1 from "@/app/api/[locale]/newsletter/unsubscribe/email";
import type emailTemplate2 from "@/app/api/[locale]/newsletter/subscribe/email";
import type emailTemplate3 from "@/app/api/[locale]/user/public/reset-password/confirm/email";
import type emailTemplate4 from "@/app/api/[locale]/user/public/reset-password/request/email";
import type emailTemplate5 from "@/app/api/[locale]/user/public/signup/email";
import type emailTemplate6 from "@/app/api/[locale]/subscription/email";
import type emailTemplate7 from "@/app/api/[locale]/users/create/email";

/**
 * Union type of all email template definitions
 * Each template has its own specific props type
 */
type AnyEmailTemplate =
  | typeof emailTemplate0
  | typeof emailTemplate1
  | typeof emailTemplate2
  | typeof emailTemplate3
  | typeof emailTemplate4
  | typeof emailTemplate5
  | typeof emailTemplate6
  | typeof emailTemplate7;

/**
 * Lazy-loaded template registry with dynamic imports
 */
const templateLoaders: Record<string, () => Promise<AnyEmailTemplate>> = {
  "contact-form": async () =>
    (await import("@/app/api/[locale]/contact/email")).default,
  "newsletter-unsubscribe": async () =>
    (await import("@/app/api/[locale]/newsletter/unsubscribe/email")).default,
  "newsletter-welcome": async () =>
    (await import("@/app/api/[locale]/newsletter/subscribe/email")).default,
  "password-reset-confirm": async () =>
    (
      await import(
        "@/app/api/[locale]/user/public/reset-password/confirm/email"
      )
    ).default,
  "password-reset-request": async () =>
    (
      await import(
        "@/app/api/[locale]/user/public/reset-password/request/email"
      )
    ).default,
  "signup-welcome": async () =>
    (await import("@/app/api/[locale]/user/public/signup/email")).default,
  "subscription-success": async () =>
    (await import("@/app/api/[locale]/subscription/email")).default,
  "user-welcome": async () =>
    (await import("@/app/api/[locale]/users/create/email")).default,
};

/**
 * Template metadata cache for fast lookups
 * Contains only metadata (id, version, name, description, category)
 * Actual components are lazy-loaded
 */
export const templateMetadataMap: Record<string, TemplateCachedMetadata> = {
  "contact-form": {
    id: "contact-form",
    version: "1.0.0",
    name: "app.api.emails.templates.contact.form.meta.name",
    description: "app.api.emails.templates.contact.form.meta.description",
    category: "contact",
    path: "/src/app/api/[locale]/contact/email.tsx",
    exampleProps: {
      name: "Max Mustermann",
      email: "max@example.com",
      company: "Musterfirma GmbH",
      subject: "Anfrage zu Ihren Dienstleistungen",
      message:
        "Ich hätte gerne weitere Informationen zu Ihren Premium-Services.",
      isForCompany: true,
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "newsletter-unsubscribe": {
    id: "newsletter-unsubscribe",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.unsubscribe.meta.name",
    description:
      "app.api.emails.templates.newsletter.unsubscribe.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/unsubscribe/email.tsx",
    exampleProps: { email: "max@example.com" },
  },
  "newsletter-welcome": {
    id: "newsletter-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.newsletter.welcome.meta.name",
    description: "app.api.emails.templates.newsletter.welcome.meta.description",
    category: "newsletter",
    path: "/src/app/api/[locale]/newsletter/subscribe/email.tsx",
    exampleProps: {
      email: "max@example.com",
      name: "Max Mustermann",
      leadId: "example-lead-id-456",
      userId: "example-user-id-123",
    },
  },
  "password-reset-confirm": {
    id: "password-reset-confirm",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.confirm.meta.name",
    description:
      "app.api.emails.templates.password.reset.confirm.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/confirm/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
    },
  },
  "password-reset-request": {
    id: "password-reset-request",
    version: "1.0.0",
    name: "app.api.emails.templates.password.reset.request.meta.name",
    description:
      "app.api.emails.templates.password.reset.request.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/reset-password/request/email.tsx",
    exampleProps: {
      publicName: "Max Mustermann",
      userId: "example-user-id-123",
      passwordResetUrl: "https://example.com/user/reset-password/token123",
    },
  },
  "signup-welcome": {
    id: "signup-welcome",
    version: "1.0.0",
    name: "app.admin.emails.templates.templates.signup.welcome.meta.name",
    description:
      "app.admin.emails.templates.templates.signup.welcome.meta.description",
    category: "auth",
    path: "/src/app/api/[locale]/user/public/signup/email.tsx",
    exampleProps: {
      privateName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
    },
  },
  "subscription-success": {
    id: "subscription-success",
    version: "1.0.0",
    name: "app.api.emails.templates.subscription.success.meta.name",
    description:
      "app.api.emails.templates.subscription.success.meta.description",
    category: "subscription",
    path: "/src/app/api/[locale]/subscription/email.tsx",
    exampleProps: {
      firstName: "Max",
      userId: "example-user-id-123",
      leadId: "example-lead-id-456",
      planName: "Premium Plan",
    },
  },
  "user-welcome": {
    id: "user-welcome",
    version: "1.0.0",
    name: "app.api.emails.templates.users.welcome.meta.name",
    description: "app.api.emails.templates.users.welcome.meta.description",
    category: "users",
    path: "/src/app/api/[locale]/users/create/email.tsx",
    exampleProps: {
      userId: "example-user-id-123",
      email: "max@example.com",
      privateName: "Max",
      publicName: "Max Mustermann",
      leadId: "example-lead-id-456",
    },
  },
};

/**
 * Get template by ID (lazy loads on first access)
 * Returns the template with its specific props type
 */
export async function getTemplate(
  id: string,
): Promise<AnyEmailTemplate | undefined> {
  const loader = templateLoaders[id];
  if (!loader) {
    return undefined;
  }

  return await loader();
}

/**
 * Get template metadata without loading the component
 */
export function getTemplateMetadata(
  id: string,
): TemplateCachedMetadata | undefined {
  return templateMetadataMap[id];
}

/**
 * Get all template IDs
 */
export function getAllTemplateIds(): string[] {
  return Object.keys(templateLoaders);
}

/**
 * Get all template metadata (fast, no component loading)
 */
export function getAllTemplateMetadata(): TemplateCachedMetadata[] {
  return Object.values(templateMetadataMap);
}

/**
 * Get templates by category (metadata only)
 */
export function getTemplatesByCategory(
  category: string,
): TemplateCachedMetadata[] {
  return getAllTemplateMetadata().filter((t) => t.category === category);
}

/**
 * Check if template exists
 */
export function hasTemplate(id: string): boolean {
  return id in templateLoaders;
}
